//! Build-script generator for a crate's **query registry** — the typed face of
//! the SQL-file convention (no SQL string in Rust source; every statement is its
//! own file under `queries/<namespace>/<name>.sql`).
//!
//! Called from an adapter's `build.rs`, [`generate`] scans the `queries/` tree
//! and writes a Rust module containing:
//!
//! - one enum per namespace directory (`queries/account/` → `enum AccountQuery`,
//!   a variant per file: `find.sql` → `Find`),
//! - a wrapper `enum Query` with one arm per namespace,
//! - `const fn sql(self) -> &'static str` on every enum, each arm an
//!   `include_str!` of its file — so the SQL is embedded at compile time and a
//!   deleted/renamed file breaks its call sites instead of drifting,
//! - `static ALL_QUERIES: &[Query]` enumerating every variant — the exact
//!   byte-for-byte corpus the binary embeds, which the `query_files_prepare`
//!   test PREPAREs against a freshly migrated database.
//!
//! Everything is derived from filenames by this one function, so a variant and
//! its path cannot disagree, and adding a query is exactly: drop the `.sql`
//! file, rebuild, use the new variant.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// Convert a `snake_case` file/dir stem to the `PascalCase` identifier it
/// becomes in the generated registry (`key_store` → `KeyStore`).
fn pascal(stem: &str) -> String {
    stem.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// One namespace directory: its `PascalCase` enum name and the sorted
/// `(VariantName, absolute_sql_path)` pairs of its files.
struct Namespace {
    enum_name: String,
    variants: Vec<(String, String)>,
}

/// Scan `queries_dir` (one subdirectory per namespace, one `.sql` file per
/// statement) and write the generated registry module to `out_file`.
///
/// The generated items are `pub` inside whatever module the consuming crate
/// `include!`s them into (by convention `pub mod queries`). Panics on any
/// malformed layout — a build script failing loudly is the point: an empty
/// namespace, a stray non-`.sql` file, or an unreadable dir must never produce
/// a silently smaller registry.
pub fn generate(queries_dir: &Path, out_file: &Path) {
    let mut namespaces: Vec<Namespace> = Vec::new();

    let mut dirs: Vec<_> = fs::read_dir(queries_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", queries_dir.display()))
        .map(|entry| entry.expect("dir entry").path())
        .collect();
    dirs.sort();

    for dir in dirs {
        assert!(
            dir.is_dir(),
            "queries/ holds one directory per namespace; found a stray file: {}",
            dir.display()
        );
        let dir_stem = dir
            .file_name()
            .expect("namespace dir name")
            .to_string_lossy()
            .into_owned();

        let mut files: Vec<_> = fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
            .map(|entry| entry.expect("dir entry").path())
            .collect();
        files.sort();

        let mut variants = Vec::new();
        for file in files {
            assert!(
                file.extension().is_some_and(|ext| ext == "sql"),
                "a namespace dir holds only .sql files; found {}",
                file.display()
            );
            let stem = file
                .file_stem()
                .expect("sql file stem")
                .to_string_lossy()
                .into_owned();
            // A manifest-relative path, emitted as
            // `include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/queries/…"))` —
            // env! expands in the consuming crate, so the generated code carries
            // no machine-specific absolute path (build reproducibility).
            let rel = format!(
                "/{}/{}/{}",
                queries_dir
                    .file_name()
                    .expect("queries dir name")
                    .to_string_lossy(),
                dir_stem,
                file.file_name().expect("sql file name").to_string_lossy()
            );
            variants.push((pascal(&stem), rel));
        }
        assert!(
            !variants.is_empty(),
            "namespace dir {} holds no .sql files — delete the dir or add the statement",
            dir.display()
        );
        namespaces.push(Namespace {
            enum_name: format!("{}Query", pascal(&dir_stem)),
            variants,
        });
    }
    assert!(
        !namespaces.is_empty(),
        "queries/ is empty — the registry would be a lie"
    );

    let mut out = String::from(
        "// Generated by query-registry-build from the crate's `queries/` tree — do not edit.\n",
    );

    // Per-namespace enums, each with its `sql()` accessor.
    for ns in &namespaces {
        let _ = writeln!(
            out,
            "\n/// One statement per variant, generated from `queries/`; \
             `sql()` is the file's contents.\n\
             #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
             pub enum {} {{",
            ns.enum_name
        );
        for (variant, _) in &ns.variants {
            let _ = writeln!(out, "    {variant},");
        }
        out.push_str("}\n");

        let _ = writeln!(
            out,
            "\nimpl {} {{\n    /// The statement's SQL, embedded from its file at compile time.\n    pub const fn sql(self) -> &'static str {{\n        match self {{",
            ns.enum_name
        );
        for (variant, path) in &ns.variants {
            let _ = writeln!(
                out,
                "            Self::{variant} => \
                 include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {path:?})),"
            );
        }
        out.push_str("        }\n    }\n}\n");
    }

    // The wrapper enum over every namespace.
    out.push_str(
        "\n/// Every query namespace in this crate — the registry's single root, \
         used for whole-corpus iteration ([`ALL_QUERIES`]).\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum Query {\n",
    );
    for ns in &namespaces {
        let arm = ns.enum_name.trim_end_matches("Query");
        let _ = writeln!(out, "    {arm}({}),", ns.enum_name);
    }
    out.push_str("}\n\nimpl Query {\n    /// The wrapped statement's SQL.\n    pub const fn sql(self) -> &'static str {\n        match self {\n");
    for ns in &namespaces {
        let arm = ns.enum_name.trim_end_matches("Query");
        let _ = writeln!(out, "            Query::{arm}(query) => query.sql(),");
    }
    out.push_str("        }\n    }\n}\n");

    // The exhaustive corpus: exactly what the binary embeds, for the prepare gate.
    out.push_str(
        "\n/// Every statement this crate embeds — the corpus the `query_files_prepare` \
         test PREPAREs against a migrated database.\n\
         pub static ALL_QUERIES: &[Query] = &[\n",
    );
    for ns in &namespaces {
        let arm = ns.enum_name.trim_end_matches("Query");
        for (variant, _) in &ns.variants {
            let _ = writeln!(out, "    Query::{arm}({}::{variant}),", ns.enum_name);
        }
    }
    out.push_str("];\n");

    fs::write(out_file, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", out_file.display()));
}
