//! PostgreSQL adapter — Zurfur's app-private data boundary.
//!
//! This crate implements the domain port traits (see [`domain::ports`]) against
//! PostgreSQL: the store for app-owned rows keyed by UUIDv7, where the rows are
//! ours to shape and mutate transactionally. It is the private counterpart to
//! `adapter-atproto`, which owns the public boundary (user-owned records on a
//! PDS). See DESIGN/"Domains and Applications" for the split.
//!
//! Per the dependency rule, everything here depends on `domain` and never the
//! reverse; the `api` crate is the composition root that decides this adapter is
//! the one wired in. Each `Pg*` type holds a cloned [`PgPool`] (an `Arc` handle,
//! cheap to clone) and is constructed from one via `new`.
//!
//! # SQL lives in `queries/`, not in Rust
//!
//! Every statement is its own file under `queries/<namespace>/<name>.sql`. The
//! committed [`queries`] module is **generated** from that tree by the
//! `query-codegen` crate (`just gen-queries`), which describes each statement
//! against a live, migrated database and emits typed functions — bind arity and
//! types are compile-checked at every call site — plus `FromRow` row structs
//! read from the real statement metadata. The `sqlx::query!` macros stay
//! retired (the workspace enables sqlx's `derive` feature, deliberately not
//! `macros`). The `codegen_current` test regenerates in CI and diffs, so stale
//! generated code fails loudly; the behavior suites exercise every statement
//! end-to-end.
//!
//! # Layout
//!
//! Writes go through the compile-enforced Unit of Work (DD `24150017`): the
//! [`PgDatabase`] factory vends a [`PgUnitOfWork`] that owns the transaction, and
//! the per-aggregate *write* views are reachable only on it. The read stores keep
//! the pool and stay non-transactional.
//!
//! - [`PgDatabase`] / [`PgUnitOfWork`] — the write factory + transaction handle
//!   ([`domain::ports::Database`] / [`domain::ports::UnitOfWork`]).
//! - [`PgAccountStore`] — account/membership reads ([`domain::ports::AccountStore`]);
//!   writes via [`PgAccountWrites`] ([`domain::ports::AccountWrites`]).
//! - [`PgCommissionStore`] — commission reads incl. the participant predicate
//!   ([`domain::ports::CommissionStore`]); writes via [`PgCommissionWrites`].
//! - [`PgChangelogStore`] — the ordered commission-changelog read
//!   ([`domain::ports::ChangelogStore`]); the append is a [`PgUnitOfWork`] view
//!   ([`PgChangelogWrites`], [`domain::ports::ChangelogWrites`]).
//! - [`PgUserStore`] — recognized-visitor reads ([`domain::ports::UserStore`]);
//!   recognition via [`PgUserWrites`] ([`domain::ports::UserWrites`]).
//! - [`PgProfileCache`] — read-through profile cache ([`domain::ports::ProfileCache`]);
//!   its best-effort `put` is pool-backed, a documented exception to the Unit of
//!   Work (a cache fill on the read path has no transactional invariant).
//! - [`PgSessionStore`] — durable tower-sessions backing store.
//!
//! Pool lifecycle and the migrations embedded from `migrations/` are owned by the
//! free functions below; the binary calls them at boot.

use std::borrow::Cow;
use std::time::Duration;

use sqlx::SqlSafeStr;
use sqlx::migrate::{Migration, MigrationType, Migrator};
use sqlx::postgres::PgPoolOptions;

/// Re-export of sqlx's connection pool so the composition root and the adapter
/// types share one `PgPool` type without `api` depending on sqlx directly. Every
/// `Pg*` repo in this crate is built from one of these (see their `new`).
pub use sqlx::PgPool;

pub mod queries;

mod account;
mod actor_identity;
mod commission;
mod commission_changelog;
mod file_store;
mod key_store;
mod key_vault;
mod plc_operation_log;
mod profile;
mod session_store;
mod uow;
mod user;
pub use account::{ACCOUNT_FACT_TABLES, ACCOUNT_NON_FACT_TABLES, PgAccountStore, PgAccountWrites};
pub use actor_identity::{PgActorIdentityStore, PgActorIdentityWrites};
pub use commission::{
    COMMISSION_FACT_TABLES, COMMISSION_NON_FACT_TABLES, PgCommissionStore, PgCommissionWrites,
};
pub use commission_changelog::{PgChangelogStore, PgChangelogWrites};
pub use file_store::PgFileStore;
pub use key_store::PgKeyStore;
pub use key_vault::RootKey;
pub use plc_operation_log::PgPlcOperationLog;
pub use profile::PgProfileCache;
pub use session_store::PgSessionStore;
pub use uow::{PgDatabase, PgUnitOfWork};
pub use user::{PgUserStore, PgUserWrites};

// Generated by build.rs:
// `static EMBEDDED_MIGRATIONS: &[(i64, &str, &str)] = &[(version, description, sql), …];`
include!(concat!(env!("OUT_DIR"), "/embedded_migrations.rs"));

/// Eagerly opens a connection pool, failing fast when the database is
/// unreachable.
///
/// Capped at 5 connections with a 5s acquire timeout. The eager connect is
/// deliberate: the binary should refuse to boot against an unreachable database
/// — [`migrate`] has to run before serving anyway — rather than surface the
/// failure on the first request.
///
/// # Caveats
///
/// - Returns `Err` if no connection can be established within the timeout; the
///   caller is expected to treat this as a fatal boot error.
/// - For an assembly path that must succeed without a live database (e.g. the
///   in-memory e2e tests), use [`lazy_pool`] instead.
///
/// # Example
///
/// ```ignore
/// let pool = adapter_pg::connect(&database_url).await?;
/// adapter_pg::migrate(&pool).await?;
/// ```
pub async fn connect(database_url: &str) -> Result<PgPool, sqlx::Error> {
    PgPoolOptions::new()
        .max_connections(5)
        .acquire_timeout(Duration::from_secs(5))
        .connect(database_url)
        .await
}

/// Builds a pool without connecting — the first query is what opens a connection.
///
/// Lets an `AppState` be assembled for routes that never touch the database (the
/// in-memory e2e tests of the sign-in flow), with no container or live server.
/// The URL is only validated for shape here, not dialed.
///
/// # Caveats
///
/// - Succeeds even against an unreachable database; any connection failure is
///   deferred to the first query. Pair with [`connect`] when you want boot to
///   fail fast instead.
/// - Returns `Err` only when `database_url` cannot be parsed into connect
///   options.
pub fn lazy_pool(database_url: &str) -> Result<PgPool, sqlx::Error> {
    PgPoolOptions::new().connect_lazy(database_url)
}

/// Runs all migrations embedded from this crate's `migrations/` directory.
///
/// Embedded at compile time by the build script (the successor to
/// `sqlx::migrate!`, which left with the retired `macros` feature), so the
/// running binary carries its schema and needs no migration files on disk.
/// Called on every boot; already-applied migrations are skipped, making it safe
/// to run unconditionally.
///
/// # Caveats
///
/// - Returns `Err` if a migration fails or the recorded migration history has
///   diverged from the embedded set (e.g. a checksum mismatch).
/// - Requires a reachable database; on a [`lazy_pool`] this is the call that
///   actually opens the connection.
pub async fn migrate(pool: &PgPool) -> Result<(), sqlx::migrate::MigrateError> {
    migrator().run(pool).await
}

/// The embedded migration set itself — the same one [`migrate`] runs.
///
/// Built from the build-script-embedded files via [`Migration::new`], which
/// computes the same SHA-384 checksum sqlx's directory resolver does — so a
/// ledger written by the old `sqlx::migrate!` embedding (or the sqlx CLI)
/// validates unchanged.
///
/// For tests that need to stop *between* migrations: a data-bearing migration
/// (e.g. ZMVP-71's root backfill) is only truly exercised against rows that
/// predate it, so its test truncates the returned set at the target version,
/// runs that, seeds, then lets [`migrate`] catch up. Production code has no
/// business with this — boot always runs the full set.
pub fn migrator() -> Migrator {
    let migrations: Vec<Migration> = EMBEDDED_MIGRATIONS
        .iter()
        .map(|(version, description, sql)| {
            Migration::new(
                *version,
                Cow::Borrowed(*description),
                MigrationType::Simple,
                // `&'static str` is `SqlSafeStr` by definition — these are our own
                // embedded migration files, not runtime input.
                (*sql).into_sql_str(),
                false,
            )
        })
        .collect();
    Migrator {
        migrations: Cow::Owned(migrations),
        ..Migrator::DEFAULT
    }
}

/// Liveness probe: `true` when a trivial `SELECT 1` round-trips within 2s.
///
/// Backs `GET /health` (200 up / 503 down). A tokio timeout is the authoritative
/// bound rather than the pool's `acquire_timeout`: a dead *cached* connection
/// fails on I/O during the query, not on acquire, so the acquire timeout alone
/// would not catch it.
///
/// # Caveats
///
/// - Never returns `Err`; any failure (timeout, connection error, query error)
///   collapses to `false`.
/// - Borderline-slow databases can flap, since the 2s bound covers acquiring a
///   connection *and* executing the query.
pub async fn is_reachable(pool: &PgPool) -> bool {
    // The tokio timeout is the authoritative bound: a dead cached connection
    // fails on I/O, not on acquire, so acquire_timeout alone is not enough.
    tokio::time::timeout(Duration::from_secs(2), queries::health::is_reachable(pool))
        .await
        .is_ok_and(|result| result.is_ok())
}
