//! PostgreSQL adapter — Zurfur's app-private data boundary. Implements the
//! domain port traits (see [`domain::ports`]) against PostgreSQL; writes go
//! through the compile-enforced Unit of Work ([`PgDatabase`]/[`PgUnitOfWork`]).
//! SQL lives in per-statement files under `queries/`, generated
//! into [`queries`] (see the crate `NODE.md`/`CLAUDE.md`).

use std::borrow::Cow;
use std::time::Duration;

use sqlx::SqlSafeStr;
use sqlx::migrate::{Migrate as _, Migration, MigrationType, Migrator};
use sqlx::postgres::PgPoolOptions;

/// The driver error a pool connect can fail with — re-exported so a
/// composition root can name it without a `sqlx` dependency of its own.
pub use sqlx::Error as SqlxError;
/// Re-export of sqlx's connection pool so the composition root and the adapter
/// types share one `PgPool` type without `api` depending on sqlx directly. Every
/// `Pg*` repo in this crate is built from one of these (see their `new`).
pub use sqlx::PgPool;

pub mod queries;

mod account;
mod actor_identity;
mod commission;
mod commission_changelog;
mod file_store;
mod key_store;
mod key_vault;
mod plc_operation_log;
mod profile;
mod session_store;
mod uow;
mod user;
mod workflow;
pub use account::{ACCOUNT_FACT_TABLES, ACCOUNT_NON_FACT_TABLES, PgAccountStore, PgAccountWrites};
pub use actor_identity::{PgActorIdentityStore, PgActorIdentityWrites};
pub use commission::{
    COMMISSION_FACT_TABLES, COMMISSION_NON_FACT_TABLES, PgCommissionStore, PgCommissionWrites,
};
pub use commission_changelog::{PgChangelogStore, PgChangelogWrites};
pub use file_store::PgFileStore;
pub use key_store::PgKeyStore;
pub use key_vault::RootKey;
pub use plc_operation_log::PgPlcOperationLog;
pub use profile::PgProfileCache;
pub use session_store::PgSessionStore;
pub use uow::{PgDatabase, PgUnitOfWork};
pub use user::{PgUserStore, PgUserWrites};
pub use workflow::{PgColumnStore, PgColumnWrites, PgWorkflowStore, PgWorkflowWrites};

// Generated by build.rs:
// `static EMBEDDED_MIGRATIONS: &[(i64, &str, &str)] = &[(version, description, sql), …];`
include!(concat!(env!("OUT_DIR"), "/embedded_migrations.rs"));

/// Eagerly opens a connection pool, capped at 5 connections with a 5s acquire
/// timeout; fails fast if the database is unreachable. Returns `Err` on
/// timeout — a fatal boot error. Use [`lazy_pool`] when a live database isn't
/// required (e.g. in-memory tests).
pub async fn connect(database_url: &str) -> Result<PgPool, sqlx::Error> {
    PgPoolOptions::new()
        .max_connections(5)
        .acquire_timeout(Duration::from_secs(5))
        .connect(database_url)
        .await
}

/// Builds a pool without connecting; the first query opens the connection.
/// Succeeds even against an unreachable database — any failure is deferred to
/// that first query. Returns `Err` only if `database_url` doesn't parse. Pair
/// with [`connect`] when boot should fail fast instead.
pub fn lazy_pool(database_url: &str) -> Result<PgPool, sqlx::Error> {
    PgPoolOptions::new().connect_lazy(database_url)
}

/// Runs all migrations embedded from this crate's `migrations/` directory,
/// compiled in at build time. Safe to call on every boot — already-applied
/// migrations are skipped. Returns `Err` on a failed migration or a checksum
/// mismatch against the recorded history.
pub async fn migrate(pool: &PgPool) -> Result<(), sqlx::migrate::MigrateError> {
    migrator().run(pool).await
}

/// The embedded migration set itself — the same one [`migrate`] runs. Tests
/// that need to stop between migrations can truncate the returned set at a
/// target version and run that subset, then let [`migrate`] catch up;
/// production code always runs the full set.
pub fn migrator() -> Migrator {
    let migrations: Vec<Migration> = EMBEDDED_MIGRATIONS
        .iter()
        .map(|(version, description, sql)| {
            Migration::new(
                *version,
                Cow::Borrowed(*description),
                MigrationType::Simple,
                // `&'static str` is `SqlSafeStr`; these are our own embedded files, not runtime input.
                (*sql).into_sql_str(),
                false,
            )
        })
        .collect();
    Migrator {
        migrations: Cow::Owned(migrations),
        ..Migrator::DEFAULT
    }
}

/// Where the database's applied migrations stand against the embedded set.
/// `api` migrates on boot; the CLI refuses to act unless
/// [`Current`](SchemaStatus::Current), forcing an explicit `zurfur migrate`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SchemaStatus {
    /// Every embedded migration is applied.
    Current,
    /// The ledger exists but `pending` embedded migrations are not applied.
    Behind { pending: usize },
    /// The ledger records `unknown` versions this binary doesn't embed; needs a newer binary.
    Ahead { unknown: usize },
    /// No migration ledger at all — a bare database.
    Unknown,
}

/// Compares the applied-migrations ledger with the embedded set. Read-only —
/// never creates the ledger table, so a bare database reads as
/// [`SchemaStatus::Unknown`] rather than being touched.
pub async fn schema_status(pool: &PgPool) -> Result<SchemaStatus, sqlx::Error> {
    let migrator = migrator();
    let ledger_exists: bool = sqlx::query_scalar("SELECT to_regclass($1) IS NOT NULL")
        .bind(format!("public.{}", migrator.table_name))
        .fetch_one(pool)
        .await?;
    if !ledger_exists {
        return Ok(SchemaStatus::Unknown);
    }
    let mut conn = pool.acquire().await?;
    let applied = conn.list_applied_migrations(&migrator.table_name).await?;
    let applied_versions: std::collections::HashSet<i64> =
        applied.iter().map(|m| m.version).collect();
    let embedded_versions: std::collections::HashSet<i64> =
        EMBEDDED_MIGRATIONS.iter().map(|(v, _, _)| *v).collect();
    let unknown = applied_versions.difference(&embedded_versions).count();
    if unknown > 0 {
        return Ok(SchemaStatus::Ahead { unknown });
    }
    let pending = embedded_versions.difference(&applied_versions).count();
    if pending == 0 {
        Ok(SchemaStatus::Current)
    } else {
        Ok(SchemaStatus::Behind { pending })
    }
}

/// Apply every pending embedded migration and report how many ran and the
/// latest embedded version. The CLI's `migrate`; `api` uses [`migrate`].
pub async fn migrate_reporting(pool: &PgPool) -> Result<MigrationReport, sqlx::Error> {
    let before = match schema_status(pool).await? {
        SchemaStatus::Behind { pending } => pending,
        SchemaStatus::Unknown => EMBEDDED_MIGRATIONS.len(),
        SchemaStatus::Current | SchemaStatus::Ahead { .. } => 0,
    };
    migrator().run(pool).await?;
    let latest = EMBEDDED_MIGRATIONS.last().map(|(v, _, _)| *v);
    let report = MigrationReport {
        applied: before,
        version: latest,
    };
    Ok(report)
}

/// What [`migrate_reporting`] did.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MigrationReport {
    /// Migrations applied by this run (`0` when already current).
    pub applied: usize,
    /// The latest embedded migration version — the schema the binary expects.
    pub version: Option<i64>,
}

/// Liveness probe: `true` when a trivial `SELECT 1` round-trips within 2s.
/// Backs `GET /health`. Never returns `Err` — any failure collapses to
/// `false`. A tokio timeout (not the pool's acquire_timeout) is the bound,
/// since a dead cached connection fails on I/O, not on acquire.
pub async fn is_reachable(pool: &PgPool) -> bool {
    tokio::time::timeout(Duration::from_secs(2), queries::health::is_reachable(pool))
        .await
        .is_ok_and(|result| result.is_ok())
}
