//! @generated by sqlx-rust-codegen — DO NOT EDIT; run `just gen-queries` to refresh.
//!
//! Typed query functions, one per `queries/<namespace>/<name>.sql`. The
//! contract is inferred from the SQL itself (pg_query parse tree + the live
//! catalog + `Executor::describe` against the migrated schema at generation
//! time); leading `--` comments in a query file become the function's docs.
#![allow(clippy::too_many_arguments)]

pub mod account {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct AcceptInvitationSeatRow {
        pub account_id: uuid::Uuid,
        pub user_id: uuid::Uuid,
        pub role: String,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct AccountInvitationsRow {
        pub id: uuid::Uuid,
        pub account_id: uuid::Uuid,
        pub invited_user: uuid::Uuid,
        pub role: String,
        pub inviter: uuid::Uuid,
        pub state: String,
        pub created_at: chrono::DateTime<chrono::Utc>,
        pub updated_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct FindRow {
        pub id: uuid::Uuid,
        pub did: Option<String>,
        pub handle: String,
        pub name: String,
        pub created_at: chrono::DateTime<chrono::Utc>,
        pub updated_at: chrono::DateTime<chrono::Utc>,
        pub deleted_at: Option<chrono::DateTime<chrono::Utc>>,
    }

    /// `queries/account/accept_invitation_flip.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// state receives the accepted state; inv_state guards the expected current
    /// (pending) state, so a concurrent flip loses.
    pub async fn accept_invitation_flip(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
        updated_at: chrono::DateTime<chrono::Utc>,
        id: uuid::Uuid,
        inv_state: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/accept_invitation_flip.sql"
        ))
        .bind(state)
        .bind(updated_at)
        .bind(id)
        .bind(inv_state)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/accept_invitation_seat.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// Seat the invited User at the offered role. If the pair is already seated (a
    /// role granted through another path, e.g. `grant_role`, while this invitation
    /// sat pending), `ON CONFLICT DO NOTHING` skips the insert and leaves the
    /// existing row untouched rather than raising a primary-key violation; RETURNING
    /// then yields no row, and the caller (`PgAccountWrites::accept_invitation`)
    /// falls back to reading the already-persisted role.
    pub async fn accept_invitation_seat(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
        parent: Option<uuid::Uuid>,
        role: &str,
        listed_on_profile: bool,
    ) -> sqlx::Result<Option<AcceptInvitationSeatRow>> {
        sqlx::query_as(include_str!(
            "../queries/account/accept_invitation_seat.sql"
        ))
        .bind(account_id)
        .bind(user_id)
        .bind(parent)
        .bind(role)
        .bind(listed_on_profile)
        .fetch_optional(conn)
        .await
    }

    /// `queries/account/change_handle_audit.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn change_handle_audit(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        account_id: uuid::Uuid,
        old_handle: &str,
        new_handle: &str,
        changed_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/change_handle_audit.sql"))
            .bind(id)
            .bind(account_id)
            .bind(old_handle)
            .bind(new_handle)
            .bind(changed_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/change_handle_repoint.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// handle receives the new handle; acc_handle guards the expected current
    /// handle, so a concurrent rename loses.
    pub async fn change_handle_repoint(
        conn: impl sqlx::PgExecutor<'_>,
        handle: &str,
        updated_at: chrono::DateTime<chrono::Utc>,
        id: uuid::Uuid,
        acc_handle: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/change_handle_repoint.sql"))
            .bind(handle)
            .bind(updated_at)
            .bind(id)
            .bind(acc_handle)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/count_handle_changes_since.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// changed_at receives the rate-limit window start (now - window).
    pub async fn count_handle_changes_since(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        changed_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<i64> {
        sqlx::query_scalar(include_str!(
            "../queries/account/count_handle_changes_since.sql"
        ))
        .bind(account_id)
        .bind(changed_at)
        .fetch_one(conn)
        .await
    }

    /// `queries/account/create_account.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// The account's DID now lives in the actor super-table (ZMVP-123): the caller interns
    /// it (keyed by this same id) as the first step of the create unit, so the projection
    /// row carries no `did`. `kind` is filled by its constant column DEFAULT ('account')
    /// and never named here. `handle` STAYS on accounts — it is the authoritative, globally
    /// unique resolution claim, not the actor_identity display cache.
    pub async fn create_account(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        handle: &str,
        name: &str,
        created_at: chrono::DateTime<chrono::Utc>,
        updated_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/create_account.sql"))
            .bind(id)
            .bind(handle)
            .bind(name)
            .bind(created_at)
            .bind(updated_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/create_invitation.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn create_invitation(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        account_id: uuid::Uuid,
        invited_user: uuid::Uuid,
        role: &str,
        inviter: uuid::Uuid,
        state: &str,
        created_at: chrono::DateTime<chrono::Utc>,
        updated_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/create_invitation.sql"))
            .bind(id)
            .bind(account_id)
            .bind(invited_user)
            .bind(role)
            .bind(inviter)
            .bind(state)
            .bind(created_at)
            .bind(updated_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/create_owner_membership.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn create_owner_membership(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
        role: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/create_owner_membership.sql"
        ))
        .bind(account_id)
        .bind(user_id)
        .bind(role)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/departure_delete_membership.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn departure_delete_membership(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/departure_delete_membership.sql"
        ))
        .bind(account_id)
        .bind(user_id)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/departure_membership.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn departure_membership(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
    ) -> sqlx::Result<Option<Option<uuid::Uuid>>> {
        sqlx::query_scalar(include_str!("../queries/account/departure_membership.sql"))
            .bind(account_id)
            .bind(user_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/account/departure_rehome_children.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// parent receives the departing member's own parent — their invitees are
    /// re-homed onto it (NULL when the departing member was a root); m_parent
    /// selects the departing member as the children's current parent.
    pub async fn departure_rehome_children(
        conn: impl sqlx::PgExecutor<'_>,
        parent: Option<uuid::Uuid>,
        account_id: uuid::Uuid,
        m_parent: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/departure_rehome_children.sql"
        ))
        .bind(parent)
        .bind(account_id)
        .bind(m_parent)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/departure_revoke_invitations.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// state receives the revoked state; inv_state selects the departing inviter's
    /// still-pending invitations.
    pub async fn departure_revoke_invitations(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
        updated_at: chrono::DateTime<chrono::Utc>,
        account_id: uuid::Uuid,
        inviter: uuid::Uuid,
        inv_state: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/departure_revoke_invitations.sql"
        ))
        .bind(state)
        .bind(updated_at)
        .bind(account_id)
        .bind(inviter)
        .bind(inv_state)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/find.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// The account's DID now lives in the actor super-table (ZMVP-123): join it back on the
    /// shared id. An account always has a DID (the per-kind CHECK on actor_identity), so a
    /// NULL here would be a corrupted projection — the adapter surfaces it as an error.
    /// LIMIT 1 is the codegen at-most-one signal: the unique cover (PK/UNIQUE)
    /// sits behind the actor_identity join, which the pg_index cardinality proof
    /// cannot cross — without it the generated contract degrades to Vec<T>.
    pub async fn find(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
    ) -> sqlx::Result<Option<FindRow>> {
        sqlx::query_as(include_str!("../queries/account/find.sql"))
            .bind(id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/account/find_did_by_handle.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// Resolve a live account's handle to its DID (ZMVP-123: the DID lives in the actor
    /// super-table now, joined on the shared id). `handle` stays the authoritative,
    /// globally unique claim on `accounts`; this backs the `/.well-known/atproto-did`
    /// resolver and the founding duplicate-handle pre-check. An account always has a DID,
    /// so `ai.did IS NOT NULL` is a true no-op that keeps the scalar result a plain DID.
    /// LIMIT 1 is the codegen at-most-one signal: the unique cover (PK/UNIQUE)
    /// sits behind the actor_identity join, which the pg_index cardinality proof
    /// cannot cross — without it the generated contract degrades to Vec<T>.
    pub async fn find_did_by_handle(
        conn: impl sqlx::PgExecutor<'_>,
        handle: &str,
    ) -> sqlx::Result<Option<String>> {
        sqlx::query_scalar(include_str!("../queries/account/find_did_by_handle.sql"))
            .bind(handle)
            .fetch_optional(conn)
            .await
    }

    /// `queries/account/find_invitation.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn find_invitation(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
    ) -> sqlx::Result<Option<AccountInvitationsRow>> {
        sqlx::query_as(include_str!("../queries/account/find_invitation.sql"))
            .bind(id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/account/find_pending_invitation.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn find_pending_invitation(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        invited_user: uuid::Uuid,
        state: &str,
    ) -> sqlx::Result<Option<AccountInvitationsRow>> {
        sqlx::query_as(include_str!(
            "../queries/account/find_pending_invitation.sql"
        ))
        .bind(account_id)
        .bind(invited_user)
        .bind(state)
        .fetch_optional(conn)
        .await
    }

    /// `queries/account/grant_role.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn grant_role(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
        role: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/grant_role.sql"))
            .bind(account_id)
            .bind(user_id)
            .bind(role)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/handle_reserved_for_other.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// changed_at receives the reservation-window start (now - quarantine window);
    /// account_id optionally excludes the renaming account itself.
    pub async fn handle_reserved_for_other(
        conn: impl sqlx::PgExecutor<'_>,
        old_handle: &str,
        changed_at: chrono::DateTime<chrono::Utc>,
        account_id: Option<uuid::Uuid>,
    ) -> sqlx::Result<bool> {
        sqlx::query_scalar(include_str!(
            "../queries/account/handle_reserved_for_other.sql"
        ))
        .bind(old_handle)
        .bind(changed_at)
        .bind(account_id)
        .fetch_one(conn)
        .await
    }

    /// `queries/account/hard_delete_account.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn hard_delete_account(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/hard_delete_account.sql"))
            .bind(id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/hard_delete_invitations.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn hard_delete_invitations(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/hard_delete_invitations.sql"
        ))
        .bind(account_id)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/hard_delete_memberships.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn hard_delete_memberships(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/hard_delete_memberships.sql"
        ))
        .bind(account_id)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/revoke_invitation.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// state receives the revoked state; inv_state guards the expected current
    /// (pending) state, so a concurrent flip loses.
    pub async fn revoke_invitation(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
        updated_at: chrono::DateTime<chrono::Utc>,
        id: uuid::Uuid,
        inv_state: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/revoke_invitation.sql"))
            .bind(state)
            .bind(updated_at)
            .bind(id)
            .bind(inv_state)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/role_of.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn role_of(
        conn: impl sqlx::PgExecutor<'_>,
        user_id: uuid::Uuid,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<Option<String>> {
        sqlx::query_scalar(include_str!("../queries/account/role_of.sql"))
            .bind(user_id)
            .bind(account_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/account/soft_delete.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// deleted_at and updated_at both receive the deletion instant ("now").
    pub async fn soft_delete(
        conn: impl sqlx::PgExecutor<'_>,
        deleted_at: Option<chrono::DateTime<chrono::Utc>>,
        updated_at: chrono::DateTime<chrono::Utc>,
        id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/soft_delete.sql"))
            .bind(deleted_at)
            .bind(updated_at)
            .bind(id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/transfer_demote_owner.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// role receives the demoted (admin) role and parent the new owner to re-home
    /// under; m_role guards that the demoted member still holds the owner role.
    pub async fn transfer_demote_owner(
        conn: impl sqlx::PgExecutor<'_>,
        role: &str,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
        parent: Option<uuid::Uuid>,
        m_role: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/transfer_demote_owner.sql"))
            .bind(role)
            .bind(account_id)
            .bind(user_id)
            .bind(parent)
            .bind(m_role)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/transfer_promote_heir.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn transfer_promote_heir(
        conn: impl sqlx::PgExecutor<'_>,
        role: &str,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/transfer_promote_heir.sql"))
            .bind(role)
            .bind(account_id)
            .bind(user_id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

pub mod actor_identity {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct ActorIdentityRow {
        pub id: uuid::Uuid,
        pub kind: String,
        pub did: Option<String>,
        pub state: String,
        pub handle: Option<String>,
        pub first_seen: chrono::DateTime<chrono::Utc>,
    }

    /// `queries/actor_identity/cache_handle.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn cache_handle(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        handle: Option<&str>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/actor_identity/cache_handle.sql"))
            .bind(id)
            .bind(handle)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/actor_identity/create.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn create(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        kind: &str,
        state: &str,
        first_seen: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/actor_identity/create.sql"))
            .bind(id)
            .bind(kind)
            .bind(state)
            .bind(first_seen)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/actor_identity/find.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn find(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
    ) -> sqlx::Result<Option<ActorIdentityRow>> {
        sqlx::query_as(include_str!("../queries/actor_identity/find.sql"))
            .bind(id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/actor_identity/find_by_did.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn find_by_did(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
    ) -> sqlx::Result<Option<ActorIdentityRow>> {
        sqlx::query_as(include_str!("../queries/actor_identity/find_by_did.sql"))
            .bind(did)
            .fetch_optional(conn)
            .await
    }

    /// `queries/actor_identity/intern.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn intern(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        kind: &str,
        did: Option<&str>,
        state: &str,
        first_seen: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<ActorIdentityRow> {
        sqlx::query_as(include_str!("../queries/actor_identity/intern.sql"))
            .bind(id)
            .bind(kind)
            .bind(did)
            .bind(state)
            .bind(first_seen)
            .fetch_one(conn)
            .await
    }
}

pub mod changelog {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct EntriesRow {
        pub seq: i64,
        pub kind: String,
        pub actor_id: Option<uuid::Uuid>,
        pub payload: serde_json::Value,
        pub note: Option<String>,
        pub created_at: chrono::DateTime<chrono::Utc>,
    }

    /// `queries/changelog/append.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn append(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        kind: &str,
        actor_id: Option<uuid::Uuid>,
        payload: &serde_json::Value,
        note: Option<&str>,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/changelog/append.sql"))
            .bind(commission_id)
            .bind(kind)
            .bind(actor_id)
            .bind(payload)
            .bind(note)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/changelog/entries.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn entries(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Vec<EntriesRow>> {
        sqlx::query_as(include_str!("../queries/changelog/entries.sql"))
            .bind(commission_id)
            .fetch_all(conn)
            .await
    }
}

pub mod commission {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct CommissionFileRow {
        pub id: uuid::Uuid,
        pub commission_id: uuid::Uuid,
        pub uploaded_by: uuid::Uuid,
        pub created_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct CommissionInvitationRow {
        pub id: uuid::Uuid,
        pub commission_id: uuid::Uuid,
        pub seat_id: uuid::Uuid,
        pub invited_user: uuid::Uuid,
        pub inviter: uuid::Uuid,
        pub state: String,
        pub created_at: chrono::DateTime<chrono::Utc>,
        pub updated_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct CurrentPlacementRow {
        pub seq: i64,
        pub account_id: uuid::Uuid,
        pub placed_by: uuid::Uuid,
        pub placed_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct FindRow {
        pub title: String,
        pub owner_id: uuid::Uuid,
        pub lifecycle: String,
        pub visibility: String,
        pub deadline: Option<chrono::DateTime<chrono::Utc>>,
        pub maturity: Option<String>,
        pub graphic: Option<bool>,
        pub direction_status: Option<String>,
        pub deadline_status: Option<String>,
        pub linked_channel: Option<String>,
        pub archived_at: Option<chrono::DateTime<chrono::Utc>>,
        pub created_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct LapsedDeadlinesRow {
        pub id: uuid::Uuid,
        pub deadline: chrono::DateTime<chrono::Utc>,
        pub deadline_status: Option<String>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct LoadTreeRow {
        pub id: uuid::Uuid,
        pub parent: Option<uuid::Uuid>,
        pub type_tag: String,
        pub mode: Option<String>,
        pub position: i32,
        pub created_by: uuid::Uuid,
        pub created_at: chrono::DateTime<chrono::Utc>,
        pub payload: serde_json::Value,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct PlacementLogRow {
        pub seq: i64,
        pub account_id: uuid::Uuid,
        pub placed_by: uuid::Uuid,
        pub placed_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct RequireSurfaceParentRow {
        pub type_tag: String,
        pub mode: Option<String>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct SeatsRow {
        pub id: uuid::Uuid,
        pub kind: String,
        pub prompt: Option<String>,
        pub link: Option<String>,
        pub occupant: Option<uuid::Uuid>,
    }

    /// `queries/commission/add_component.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn add_component(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        parent: Option<uuid::Uuid>,
        created_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
        payload: &serde_json::Value,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/add_component.sql"))
            .bind(id)
            .bind(commission_id)
            .bind(parent)
            .bind(created_by)
            .bind(created_at)
            .bind(payload)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/add_file.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn add_file(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        uploaded_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/add_file.sql"))
            .bind(id)
            .bind(commission_id)
            .bind(uploaded_by)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/add_participant.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// Insert a participant membership row (ZMVP-76). `(commission_id, user_id)`
    /// is the table's PRIMARY KEY, so a re-add for an already-seated pair is a
    /// silent no-op rather than a constraint violation: the owner's row is born
    /// here (CommissionWrites::create) and ZMVP-79's seat acceptance re-adds
    /// whoever it seats, who may already be a participant through another seat (a
    /// User can hold multiple seats, Engineer ruling 2026-07-16) — the invariant
    /// of at most one membership row per pair is unreachable to violate rather
    /// than caller discipline. The original `created_at` is preserved.
    pub async fn add_participant(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        user_id: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/add_participant.sql"))
            .bind(commission_id)
            .bind(user_id)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/add_surface.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn add_surface(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        parent: Option<uuid::Uuid>,
        mode: Option<&str>,
        created_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/add_surface.sql"))
            .bind(id)
            .bind(commission_id)
            .bind(parent)
            .bind(mode)
            .bind(created_by)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/create_commission.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn create_commission(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        title: &str,
        owner_id: uuid::Uuid,
        lifecycle: &str,
        visibility: &str,
        deadline: Option<chrono::DateTime<chrono::Utc>>,
        maturity: Option<&str>,
        graphic: Option<bool>,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/create_commission.sql"))
            .bind(id)
            .bind(title)
            .bind(owner_id)
            .bind(lifecycle)
            .bind(visibility)
            .bind(deadline)
            .bind(maturity)
            .bind(graphic)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/create_root_surface.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn create_root_surface(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        mode: Option<&str>,
        created_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/create_root_surface.sql"
        ))
        .bind(id)
        .bind(commission_id)
        .bind(mode)
        .bind(created_by)
        .bind(created_at)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/create_seat_invitation.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// Persist a freshly issued, pending seat invitation (ZMVP-78). The partial
    /// unique index (`... WHERE state = 'pending'`, see the migration) enforces at
    /// most one pending offer per (seat, invited_user), so a duplicate issue is
    /// silently dropped rather than becoming a second row — the store-level backstop
    /// for the idempotent re-invite the handler also guards. The Seat mirror of
    /// `account/create_invitation.sql`.
    pub async fn create_seat_invitation(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        seat_id: uuid::Uuid,
        invited_user: uuid::Uuid,
        inviter: uuid::Uuid,
        state: &str,
        created_at: chrono::DateTime<chrono::Utc>,
        updated_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/create_seat_invitation.sql"
        ))
        .bind(id)
        .bind(commission_id)
        .bind(seat_id)
        .bind(invited_user)
        .bind(inviter)
        .bind(state)
        .bind(created_at)
        .bind(updated_at)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/current_placement.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn current_placement(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Option<CurrentPlacementRow>> {
        sqlx::query_as(include_str!("../queries/commission/current_placement.sql"))
            .bind(commission_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/commission/declare_seat_node.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn declare_seat_node(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        parent: Option<uuid::Uuid>,
        created_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/declare_seat_node.sql"))
            .bind(id)
            .bind(commission_id)
            .bind(parent)
            .bind(created_by)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/declare_seat_satellite.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn declare_seat_satellite(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        kind: &str,
        prompt: Option<&str>,
        link: Option<&str>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/declare_seat_satellite.sql"
        ))
        .bind(id)
        .bind(commission_id)
        .bind(kind)
        .bind(prompt)
        .bind(link)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/declare_slot_node.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn declare_slot_node(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        parent: Option<uuid::Uuid>,
        created_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/declare_slot_node.sql"))
            .bind(id)
            .bind(commission_id)
            .bind(parent)
            .bind(created_by)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/declare_slot_satellite.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn declare_slot_satellite(
        conn: impl sqlx::PgExecutor<'_>,
        node_id: uuid::Uuid,
        commission_id: uuid::Uuid,
        title: &str,
        notes: Option<&str>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/declare_slot_satellite.sql"
        ))
        .bind(node_id)
        .bind(commission_id)
        .bind(title)
        .bind(notes)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/delete.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn delete(conn: impl sqlx::PgExecutor<'_>, id: uuid::Uuid) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/delete.sql"))
            .bind(id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/find.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn find(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
    ) -> sqlx::Result<Option<FindRow>> {
        sqlx::query_as(include_str!("../queries/commission/find.sql"))
            .bind(id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/commission/find_file.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn find_file(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Option<CommissionFileRow>> {
        sqlx::query_as(include_str!("../queries/commission/find_file.sql"))
            .bind(id)
            .bind(commission_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/commission/find_pending_seat_invitation.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// The lone pending offer for (commission, seat, invited_user), or nothing
    /// (ZMVP-78). The `state` bind is the pending discriminant; accepted/revoked
    /// invitations are history, not live offers, so they never match. Scoped to
    /// commission_id in the query itself so a seat id from another commission's
    /// tree can never reach that commission's offers — the authorization binding
    /// is unrepresentable to skip, not caller discipline. The Seat mirror of
    /// `account/find_pending_invitation.sql`.
    pub async fn find_pending_seat_invitation(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        seat_id: uuid::Uuid,
        invited_user: uuid::Uuid,
        state: &str,
    ) -> sqlx::Result<Option<CommissionInvitationRow>> {
        sqlx::query_as(include_str!(
            "../queries/commission/find_pending_seat_invitation.sql"
        ))
        .bind(commission_id)
        .bind(seat_id)
        .bind(invited_user)
        .bind(state)
        .fetch_optional(conn)
        .await
    }

    /// `queries/commission/grant_view.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn grant_view(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        account_id: uuid::Uuid,
        level: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/grant_view.sql"))
            .bind(commission_id)
            .bind(account_id)
            .bind(level)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/is_participant.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn is_participant(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        user_id: uuid::Uuid,
    ) -> sqlx::Result<bool> {
        sqlx::query_scalar(include_str!("../queries/commission/is_participant.sql"))
            .bind(commission_id)
            .bind(user_id)
            .fetch_one(conn)
            .await
    }

    /// `queries/commission/lapsed_deadlines.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// The deadline param receives the sweep instant ("now"); lifecycle takes the
    /// terminal lifecycles exempt from lapsing.
    pub async fn lapsed_deadlines(
        conn: impl sqlx::PgExecutor<'_>,
        deadline: chrono::DateTime<chrono::Utc>,
        lifecycle: &[String],
    ) -> sqlx::Result<Vec<LapsedDeadlinesRow>> {
        sqlx::query_as(include_str!("../queries/commission/lapsed_deadlines.sql"))
            .bind(deadline)
            .bind(lifecycle)
            .fetch_all(conn)
            .await
    }

    /// `queries/commission/load_tree.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn load_tree(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Vec<LoadTreeRow>> {
        sqlx::query_as(include_str!("../queries/commission/load_tree.sql"))
            .bind(commission_id)
            .fetch_all(conn)
            .await
    }

    /// `queries/commission/place_append.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn place_append(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        account_id: uuid::Uuid,
        placed_by: uuid::Uuid,
        placed_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<i64> {
        sqlx::query_scalar(include_str!("../queries/commission/place_append.sql"))
            .bind(commission_id)
            .bind(account_id)
            .bind(placed_by)
            .bind(placed_at)
            .fetch_one(conn)
            .await
    }

    /// `queries/commission/place_repoint_current.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn place_repoint_current(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        account_id: uuid::Uuid,
        seq: i64,
        placed_by: uuid::Uuid,
        placed_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/place_repoint_current.sql"
        ))
        .bind(commission_id)
        .bind(account_id)
        .bind(seq)
        .bind(placed_by)
        .bind(placed_at)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/placement_log.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn placement_log(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Vec<PlacementLogRow>> {
        sqlx::query_as(include_str!("../queries/commission/placement_log.sql"))
            .bind(commission_id)
            .fetch_all(conn)
            .await
    }

    /// `queries/commission/remove_node_delete.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn remove_node_delete(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/remove_node_delete.sql"))
            .bind(id)
            .bind(commission_id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/remove_node_gate.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn remove_node_gate(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Option<Option<uuid::Uuid>>> {
        sqlx::query_scalar(include_str!("../queries/commission/remove_node_gate.sql"))
            .bind(id)
            .bind(commission_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/commission/remove_node_renumber.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn remove_node_renumber(
        conn: impl sqlx::PgExecutor<'_>,
        parent: uuid::Uuid,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/remove_node_renumber.sql"
        ))
        .bind(parent)
        .bind(commission_id)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/require_surface_parent.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn require_surface_parent(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Option<RequireSurfaceParentRow>> {
        sqlx::query_as(include_str!(
            "../queries/commission/require_surface_parent.sql"
        ))
        .bind(id)
        .bind(commission_id)
        .fetch_optional(conn)
        .await
    }

    /// `queries/commission/revoke_seat_invitation.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// Revoke a pending seat invitation (ZMVP-78). state receives the revoked state;
    /// inv_state guards the expected current (pending) state, so a concurrent flip
    /// loses, and an UPDATE matching no row still succeeds — revoking an absent or
    /// already-terminal invitation is a harmless no-op. The Seat mirror of
    /// `account/revoke_invitation.sql`.
    pub async fn revoke_seat_invitation(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
        updated_at: chrono::DateTime<chrono::Utc>,
        id: uuid::Uuid,
        inv_state: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/revoke_seat_invitation.sql"
        ))
        .bind(state)
        .bind(updated_at)
        .bind(id)
        .bind(inv_state)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/revoke_view.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn revoke_view(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/revoke_view.sql"))
            .bind(commission_id)
            .bind(account_id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/seats.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn seats(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Vec<SeatsRow>> {
        sqlx::query_as(include_str!("../queries/commission/seats.sql"))
            .bind(commission_id)
            .fetch_all(conn)
            .await
    }

    /// `queries/commission/set_archived.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn set_archived(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        archived_at: Option<chrono::DateTime<chrono::Utc>>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/set_archived.sql"))
            .bind(id)
            .bind(archived_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/set_deadline.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn set_deadline(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        deadline: Option<chrono::DateTime<chrono::Utc>>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/set_deadline.sql"))
            .bind(id)
            .bind(deadline)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/set_deadline_status.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn set_deadline_status(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        deadline_status: Option<&str>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/set_deadline_status.sql"
        ))
        .bind(id)
        .bind(deadline_status)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/set_direction_status.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn set_direction_status(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        direction_status: Option<&str>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/set_direction_status.sql"
        ))
        .bind(id)
        .bind(direction_status)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/set_linked_channel.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn set_linked_channel(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        linked_channel: Option<&str>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/set_linked_channel.sql"))
            .bind(id)
            .bind(linked_channel)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/set_maturity.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn set_maturity(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        maturity: Option<&str>,
        graphic: Option<bool>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/set_maturity.sql"))
            .bind(id)
            .bind(maturity)
            .bind(graphic)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/view_grant.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn view_grant(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<Option<String>> {
        sqlx::query_scalar(include_str!("../queries/commission/view_grant.sql"))
            .bind(commission_id)
            .bind(account_id)
            .fetch_optional(conn)
            .await
    }
}

pub mod file {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct GetRow {
        pub filename: String,
        pub content_type: String,
        pub byte_size: i64,
        pub bytes: Vec<u8>,
    }

    /// `queries/file/delete.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn delete(conn: impl sqlx::PgExecutor<'_>, key: uuid::Uuid) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/file/delete.sql"))
            .bind(key)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/file/get.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn get(
        conn: impl sqlx::PgExecutor<'_>,
        key: uuid::Uuid,
    ) -> sqlx::Result<Option<GetRow>> {
        sqlx::query_as(include_str!("../queries/file/get.sql"))
            .bind(key)
            .fetch_optional(conn)
            .await
    }

    /// `queries/file/put.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn put(
        conn: impl sqlx::PgExecutor<'_>,
        key: uuid::Uuid,
        filename: &str,
        content_type: &str,
        byte_size: i64,
        bytes: &[u8],
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/file/put.sql"))
            .bind(key)
            .bind(filename)
            .bind(content_type)
            .bind(byte_size)
            .bind(bytes)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

pub mod health {
    /// `queries/health/is_reachable.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn is_reachable(conn: impl sqlx::PgExecutor<'_>) -> sqlx::Result<i32> {
        sqlx::query_scalar(include_str!("../queries/health/is_reachable.sql"))
            .fetch_one(conn)
            .await
    }
}

pub mod key_store {
    /// `queries/key_store/get.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn get(conn: impl sqlx::PgExecutor<'_>, did: &str) -> sqlx::Result<Option<Vec<u8>>> {
        sqlx::query_scalar(include_str!("../queries/key_store/get.sql"))
            .bind(did)
            .fetch_optional(conn)
            .await
    }

    /// `queries/key_store/put.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn put(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
        wrapped_keys: &[u8],
        key_version: i32,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/key_store/put.sql"))
            .bind(did)
            .bind(wrapped_keys)
            .bind(key_version)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

pub mod plc {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct LatestOpRow {
        pub cid: String,
        pub op_type: String,
        pub prev: Option<String>,
        pub operation: serde_json::Value,
    }

    /// `queries/plc/append.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn append(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
        cid: &str,
        r#type: &str,
        prev: Option<&str>,
        operation: &serde_json::Value,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/plc/append.sql"))
            .bind(did)
            .bind(cid)
            .bind(r#type)
            .bind(prev)
            .bind(operation)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/plc/latest_cid.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn latest_cid(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
    ) -> sqlx::Result<Option<String>> {
        sqlx::query_scalar(include_str!("../queries/plc/latest_cid.sql"))
            .bind(did)
            .fetch_optional(conn)
            .await
    }

    /// `queries/plc/latest_op.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn latest_op(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
    ) -> sqlx::Result<Option<LatestOpRow>> {
        sqlx::query_as(include_str!("../queries/plc/latest_op.sql"))
            .bind(did)
            .fetch_optional(conn)
            .await
    }
}

pub mod profile {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct GetRow {
        pub did: String,
        pub handle: String,
        pub display_name: Option<String>,
        pub avatar_url: Option<String>,
    }

    /// `queries/profile/get.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// fetched_at receives the staleness cutoff (now - TTL); older cache rows miss.
    pub async fn get(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
        fetched_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<Option<GetRow>> {
        sqlx::query_as(include_str!("../queries/profile/get.sql"))
            .bind(did)
            .bind(fetched_at)
            .fetch_optional(conn)
            .await
    }

    /// `queries/profile/put.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn put(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
        handle: &str,
        display_name: Option<&str>,
        avatar_url: Option<&str>,
        fetched_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/profile/put.sql"))
            .bind(did)
            .bind(handle)
            .bind(display_name)
            .bind(avatar_url)
            .bind(fetched_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

pub mod session {
    /// `queries/session/create.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn create(
        conn: impl sqlx::PgExecutor<'_>,
        id: &str,
        data: &[u8],
        expiry_date: time::OffsetDateTime,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/session/create.sql"))
            .bind(id)
            .bind(data)
            .bind(expiry_date)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/session/delete.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn delete(conn: impl sqlx::PgExecutor<'_>, id: &str) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/session/delete.sql"))
            .bind(id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/session/delete_expired.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// expiry_date receives the sweep instant ("now").
    pub async fn delete_expired(
        conn: impl sqlx::PgExecutor<'_>,
        expiry_date: time::OffsetDateTime,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/session/delete_expired.sql"))
            .bind(expiry_date)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/session/load.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// expiry_date receives the load instant ("now"); expired sessions miss.
    pub async fn load(
        conn: impl sqlx::PgExecutor<'_>,
        id: &str,
        expiry_date: time::OffsetDateTime,
    ) -> sqlx::Result<Option<Vec<u8>>> {
        sqlx::query_scalar(include_str!("../queries/session/load.sql"))
            .bind(id)
            .bind(expiry_date)
            .fetch_optional(conn)
            .await
    }

    /// `queries/session/save.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn save(
        conn: impl sqlx::PgExecutor<'_>,
        id: &str,
        data: &[u8],
        expiry_date: time::OffsetDateTime,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/session/save.sql"))
            .bind(id)
            .bind(data)
            .bind(expiry_date)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

pub mod user {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct FindByDidRow {
        pub id: uuid::Uuid,
        pub created_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct FindRow {
        pub id: uuid::Uuid,
        pub did: Option<String>,
        pub created_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct ProvisionRow {
        pub id: uuid::Uuid,
        pub created_at: chrono::DateTime<chrono::Utc>,
    }

    /// `queries/user/find.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// The visitor's DID now lives in the actor super-table (ZMVP-123): join it back on
    /// the shared id. A User always has a DID (the per-kind CHECK on actor_identity), so a
    /// NULL here would be a corrupted projection — the adapter surfaces it as an error.
    /// LIMIT 1 is the codegen at-most-one signal: the unique cover (PK/UNIQUE)
    /// sits behind the actor_identity join, which the pg_index cardinality proof
    /// cannot cross — without it the generated contract degrades to Vec<T>.
    pub async fn find(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
    ) -> sqlx::Result<Option<FindRow>> {
        sqlx::query_as(include_str!("../queries/user/find.sql"))
            .bind(id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/user/find_by_did.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// Resolve a DID to its User via the actor super-table (ZMVP-123: the DID lives there
    /// now, not on `users`). The caller already holds the DID it looked up, so the row need
    /// only carry the projection's own columns — the adapter pairs them with that DID.
    /// LIMIT 1 is the codegen at-most-one signal: the unique cover (PK/UNIQUE)
    /// sits behind the actor_identity join, which the pg_index cardinality proof
    /// cannot cross — without it the generated contract degrades to Vec<T>.
    pub async fn find_by_did(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
    ) -> sqlx::Result<Option<FindByDidRow>> {
        sqlx::query_as(include_str!("../queries/user/find_by_did.sql"))
            .bind(did)
            .fetch_optional(conn)
            .await
    }

    /// `queries/user/provision.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// Insert (or resolve) the User projection row keyed by its shared actor_identity id —
    /// the id the caller has just interned the visitor's DID under (ZMVP-123). The DID and
    /// the one-DID-one-actor race are the intern step's job now; this only lands the
    /// projection. Idempotent on the shared PK: a repeat sign-in resolves to the same
    /// identity id, whose users row already exists, so the no-op DO UPDATE lets RETURNING
    /// hand back the ORIGINAL created_at. `kind` is filled by its constant column DEFAULT
    /// ('user') and never named here.
    pub async fn provision(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<ProvisionRow> {
        sqlx::query_as(include_str!("../queries/user/provision.sql"))
            .bind(id)
            .bind(created_at)
            .fetch_one(conn)
            .await
    }
}

/// Every statement containing an INSERT/UPDATE/DELETE (CTEs included), as
/// `namespace::function` — structural classification from the parse tree.
pub static WRITE_QUERY_FNS: &[&str] = &[
    "account::accept_invitation_flip",
    "account::accept_invitation_seat",
    "account::change_handle_audit",
    "account::change_handle_repoint",
    "account::create_account",
    "account::create_invitation",
    "account::create_owner_membership",
    "account::departure_delete_membership",
    "account::departure_rehome_children",
    "account::departure_revoke_invitations",
    "account::grant_role",
    "account::hard_delete_account",
    "account::hard_delete_invitations",
    "account::hard_delete_memberships",
    "account::revoke_invitation",
    "account::soft_delete",
    "account::transfer_demote_owner",
    "account::transfer_promote_heir",
    "actor_identity::cache_handle",
    "actor_identity::create",
    "actor_identity::intern",
    "changelog::append",
    "commission::add_component",
    "commission::add_file",
    "commission::add_participant",
    "commission::add_surface",
    "commission::create_commission",
    "commission::create_root_surface",
    "commission::create_seat_invitation",
    "commission::declare_seat_node",
    "commission::declare_seat_satellite",
    "commission::declare_slot_node",
    "commission::declare_slot_satellite",
    "commission::delete",
    "commission::grant_view",
    "commission::place_append",
    "commission::place_repoint_current",
    "commission::remove_node_delete",
    "commission::remove_node_renumber",
    "commission::revoke_seat_invitation",
    "commission::revoke_view",
    "commission::set_archived",
    "commission::set_deadline",
    "commission::set_deadline_status",
    "commission::set_direction_status",
    "commission::set_linked_channel",
    "commission::set_maturity",
    "file::delete",
    "file::put",
    "key_store::put",
    "plc::append",
    "profile::put",
    "session::create",
    "session::delete",
    "session::delete_expired",
    "session::save",
    "user::provision",
];
