//! @generated by query-codegen — DO NOT EDIT; run `just gen-queries` to refresh.
//!
//! Typed query functions, one per `queries/<namespace>/<name>.sql`, with
//! parameter and row types read from the live, migrated schema at generation
//! time (`Executor::describe`). Staleness is caught by the `codegen_current`
//! test, which regenerates against a fresh container and diffs this file.
#![allow(clippy::too_many_arguments)]

pub mod account {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct AccountRow {
        pub id: uuid::Uuid,
        pub did: String,
        pub handle: String,
        pub name: String,
        pub created_at: chrono::DateTime<chrono::Utc>,
        pub updated_at: chrono::DateTime<chrono::Utc>,
        pub deleted_at: Option<chrono::DateTime<chrono::Utc>>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct InvitationRow {
        pub id: uuid::Uuid,
        pub account_id: uuid::Uuid,
        pub invited_user: uuid::Uuid,
        pub role: String,
        pub inviter: uuid::Uuid,
        pub state: String,
        pub created_at: chrono::DateTime<chrono::Utc>,
        pub updated_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct SeatedMemberRow {
        pub account_id: uuid::Uuid,
        pub user_id: uuid::Uuid,
        pub role: String,
    }

    /// `queries/account/accept_invitation_flip.sql`, typed against the migrated schema at generation time.
    pub async fn accept_invitation_flip(
        conn: impl sqlx::PgExecutor<'_>,
        accepted_state: &str,
        updated_at: chrono::DateTime<chrono::Utc>,
        id: uuid::Uuid,
        pending_state: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/accept_invitation_flip.sql"
        ))
        .bind(accepted_state)
        .bind(updated_at)
        .bind(id)
        .bind(pending_state)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/accept_invitation_seat.sql`, typed against the migrated schema at generation time.
    pub async fn accept_invitation_seat(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
        parent: uuid::Uuid,
        role: &str,
        listed_on_profile: bool,
    ) -> sqlx::Result<SeatedMemberRow> {
        sqlx::query_as(include_str!(
            "../queries/account/accept_invitation_seat.sql"
        ))
        .bind(account_id)
        .bind(user_id)
        .bind(parent)
        .bind(role)
        .bind(listed_on_profile)
        .fetch_one(conn)
        .await
    }

    /// `queries/account/change_handle_audit.sql`, typed against the migrated schema at generation time.
    pub async fn change_handle_audit(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        account_id: uuid::Uuid,
        old_handle: &str,
        new_handle: &str,
        changed_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/change_handle_audit.sql"))
            .bind(id)
            .bind(account_id)
            .bind(old_handle)
            .bind(new_handle)
            .bind(changed_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/change_handle_repoint.sql`, typed against the migrated schema at generation time.
    pub async fn change_handle_repoint(
        conn: impl sqlx::PgExecutor<'_>,
        new_handle: &str,
        at: chrono::DateTime<chrono::Utc>,
        account_id: uuid::Uuid,
        old_handle: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/change_handle_repoint.sql"))
            .bind(new_handle)
            .bind(at)
            .bind(account_id)
            .bind(old_handle)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/count_handle_changes_since.sql`, typed against the migrated schema at generation time.
    pub async fn count_handle_changes_since(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        since: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<i64> {
        sqlx::query_scalar(include_str!(
            "../queries/account/count_handle_changes_since.sql"
        ))
        .bind(account_id)
        .bind(since)
        .fetch_one(conn)
        .await
    }

    /// `queries/account/create_account.sql`, typed against the migrated schema at generation time.
    pub async fn create_account(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        did: &str,
        handle: &str,
        name: &str,
        created_at: chrono::DateTime<chrono::Utc>,
        updated_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/create_account.sql"))
            .bind(id)
            .bind(did)
            .bind(handle)
            .bind(name)
            .bind(created_at)
            .bind(updated_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/create_invitation.sql`, typed against the migrated schema at generation time.
    pub async fn create_invitation(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        account_id: uuid::Uuid,
        invited_user: uuid::Uuid,
        role: &str,
        inviter: uuid::Uuid,
        state: &str,
        created_at: chrono::DateTime<chrono::Utc>,
        updated_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/create_invitation.sql"))
            .bind(id)
            .bind(account_id)
            .bind(invited_user)
            .bind(role)
            .bind(inviter)
            .bind(state)
            .bind(created_at)
            .bind(updated_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/create_owner_membership.sql`, typed against the migrated schema at generation time.
    pub async fn create_owner_membership(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
        role: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/create_owner_membership.sql"
        ))
        .bind(account_id)
        .bind(user_id)
        .bind(role)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/departure_delete_membership.sql`, typed against the migrated schema at generation time.
    pub async fn departure_delete_membership(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/departure_delete_membership.sql"
        ))
        .bind(account_id)
        .bind(user_id)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/departure_membership.sql`, typed against the migrated schema at generation time.
    pub async fn departure_membership(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
    ) -> sqlx::Result<Option<Option<uuid::Uuid>>> {
        sqlx::query_scalar(include_str!("../queries/account/departure_membership.sql"))
            .bind(account_id)
            .bind(user_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/account/departure_rehome_children.sql`, typed against the migrated schema at generation time.
    pub async fn departure_rehome_children(
        conn: impl sqlx::PgExecutor<'_>,
        parent: Option<uuid::Uuid>,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/departure_rehome_children.sql"
        ))
        .bind(parent)
        .bind(account_id)
        .bind(user_id)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/departure_revoke_invitations.sql`, typed against the migrated schema at generation time.
    pub async fn departure_revoke_invitations(
        conn: impl sqlx::PgExecutor<'_>,
        revoked_state: &str,
        updated_at: chrono::DateTime<chrono::Utc>,
        account_id: uuid::Uuid,
        inviter: uuid::Uuid,
        pending_state: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/departure_revoke_invitations.sql"
        ))
        .bind(revoked_state)
        .bind(updated_at)
        .bind(account_id)
        .bind(inviter)
        .bind(pending_state)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/find.sql`, typed against the migrated schema at generation time.
    pub async fn find(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
    ) -> sqlx::Result<Option<AccountRow>> {
        sqlx::query_as(include_str!("../queries/account/find.sql"))
            .bind(id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/account/find_did_by_handle.sql`, typed against the migrated schema at generation time.
    pub async fn find_did_by_handle(
        conn: impl sqlx::PgExecutor<'_>,
        handle: &str,
    ) -> sqlx::Result<Option<String>> {
        sqlx::query_scalar(include_str!("../queries/account/find_did_by_handle.sql"))
            .bind(handle)
            .fetch_optional(conn)
            .await
    }

    /// `queries/account/find_invitation.sql`, typed against the migrated schema at generation time.
    pub async fn find_invitation(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
    ) -> sqlx::Result<Option<InvitationRow>> {
        sqlx::query_as(include_str!("../queries/account/find_invitation.sql"))
            .bind(id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/account/find_pending_invitation.sql`, typed against the migrated schema at generation time.
    pub async fn find_pending_invitation(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        invited_user: uuid::Uuid,
        state: &str,
    ) -> sqlx::Result<Option<InvitationRow>> {
        sqlx::query_as(include_str!(
            "../queries/account/find_pending_invitation.sql"
        ))
        .bind(account_id)
        .bind(invited_user)
        .bind(state)
        .fetch_optional(conn)
        .await
    }

    /// `queries/account/grant_role.sql`, typed against the migrated schema at generation time.
    pub async fn grant_role(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
        user_id: uuid::Uuid,
        role: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/grant_role.sql"))
            .bind(account_id)
            .bind(user_id)
            .bind(role)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/handle_reserved_for_other.sql`, typed against the migrated schema at generation time.
    pub async fn handle_reserved_for_other(
        conn: impl sqlx::PgExecutor<'_>,
        old_handle: &str,
        since: chrono::DateTime<chrono::Utc>,
        excluding: Option<uuid::Uuid>,
    ) -> sqlx::Result<bool> {
        sqlx::query_scalar(include_str!(
            "../queries/account/handle_reserved_for_other.sql"
        ))
        .bind(old_handle)
        .bind(since)
        .bind(excluding)
        .fetch_one(conn)
        .await
    }

    /// `queries/account/hard_delete_account.sql`, typed against the migrated schema at generation time.
    pub async fn hard_delete_account(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/hard_delete_account.sql"))
            .bind(account_id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/hard_delete_invitations.sql`, typed against the migrated schema at generation time.
    pub async fn hard_delete_invitations(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/hard_delete_invitations.sql"
        ))
        .bind(account_id)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/hard_delete_memberships.sql`, typed against the migrated schema at generation time.
    pub async fn hard_delete_memberships(
        conn: impl sqlx::PgExecutor<'_>,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/account/hard_delete_memberships.sql"
        ))
        .bind(account_id)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/account/revoke_invitation.sql`, typed against the migrated schema at generation time.
    pub async fn revoke_invitation(
        conn: impl sqlx::PgExecutor<'_>,
        revoked_state: &str,
        updated_at: chrono::DateTime<chrono::Utc>,
        id: uuid::Uuid,
        pending_state: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/revoke_invitation.sql"))
            .bind(revoked_state)
            .bind(updated_at)
            .bind(id)
            .bind(pending_state)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/role_of.sql`, typed against the migrated schema at generation time.
    pub async fn role_of(
        conn: impl sqlx::PgExecutor<'_>,
        user_id: uuid::Uuid,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<Option<String>> {
        sqlx::query_scalar(include_str!("../queries/account/role_of.sql"))
            .bind(user_id)
            .bind(account_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/account/soft_delete.sql`, typed against the migrated schema at generation time.
    pub async fn soft_delete(
        conn: impl sqlx::PgExecutor<'_>,
        now: chrono::DateTime<chrono::Utc>,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/soft_delete.sql"))
            .bind(now)
            .bind(account_id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/transfer_demote_owner.sql`, typed against the migrated schema at generation time.
    pub async fn transfer_demote_owner(
        conn: impl sqlx::PgExecutor<'_>,
        admin_role: &str,
        account_id: uuid::Uuid,
        old_owner: uuid::Uuid,
        new_owner: uuid::Uuid,
        owner_role: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/transfer_demote_owner.sql"))
            .bind(admin_role)
            .bind(account_id)
            .bind(old_owner)
            .bind(new_owner)
            .bind(owner_role)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/account/transfer_promote_heir.sql`, typed against the migrated schema at generation time.
    pub async fn transfer_promote_heir(
        conn: impl sqlx::PgExecutor<'_>,
        owner_role: &str,
        account_id: uuid::Uuid,
        new_owner: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/account/transfer_promote_heir.sql"))
            .bind(owner_role)
            .bind(account_id)
            .bind(new_owner)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

pub mod actor_identity {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct ActorIdentityRow {
        pub id: uuid::Uuid,
        pub kind: String,
        pub did: Option<String>,
        pub state: String,
    }

    /// `queries/actor_identity/create.sql`, typed against the migrated schema at generation time.
    pub async fn create(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        kind: &str,
        state: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/actor_identity/create.sql"))
            .bind(id)
            .bind(kind)
            .bind(state)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/actor_identity/find.sql`, typed against the migrated schema at generation time.
    pub async fn find(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
    ) -> sqlx::Result<Option<ActorIdentityRow>> {
        sqlx::query_as(include_str!("../queries/actor_identity/find.sql"))
            .bind(id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/actor_identity/find_by_did.sql`, typed against the migrated schema at generation time.
    pub async fn find_by_did(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
    ) -> sqlx::Result<Option<ActorIdentityRow>> {
        sqlx::query_as(include_str!("../queries/actor_identity/find_by_did.sql"))
            .bind(did)
            .fetch_optional(conn)
            .await
    }

    /// `queries/actor_identity/intern.sql`, typed against the migrated schema at generation time.
    pub async fn intern(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        kind: &str,
        did: &str,
        state: &str,
    ) -> sqlx::Result<ActorIdentityRow> {
        sqlx::query_as(include_str!("../queries/actor_identity/intern.sql"))
            .bind(id)
            .bind(kind)
            .bind(did)
            .bind(state)
            .fetch_one(conn)
            .await
    }
}

pub mod changelog {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct ChangelogRow {
        pub seq: i64,
        pub kind: String,
        pub actor_id: Option<uuid::Uuid>,
        pub payload: serde_json::Value,
        pub note: Option<String>,
        pub created_at: chrono::DateTime<chrono::Utc>,
    }

    /// `queries/changelog/append.sql`, typed against the migrated schema at generation time.
    pub async fn append(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        kind: &str,
        actor_id: Option<uuid::Uuid>,
        payload: &serde_json::Value,
        note: Option<&str>,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/changelog/append.sql"))
            .bind(commission_id)
            .bind(kind)
            .bind(actor_id)
            .bind(payload)
            .bind(note)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/changelog/entries.sql`, typed against the migrated schema at generation time.
    pub async fn entries(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Vec<ChangelogRow>> {
        sqlx::query_as(include_str!("../queries/changelog/entries.sql"))
            .bind(commission_id)
            .fetch_all(conn)
            .await
    }
}

pub mod commission {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct CommissionFileRow {
        pub id: uuid::Uuid,
        pub commission_id: uuid::Uuid,
        pub uploaded_by: uuid::Uuid,
        pub created_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct CommissionRow {
        pub title: String,
        pub owner_id: uuid::Uuid,
        pub lifecycle: String,
        pub visibility: String,
        pub deadline: Option<chrono::DateTime<chrono::Utc>>,
        pub maturity: Option<String>,
        pub graphic: Option<bool>,
        pub direction_status: Option<String>,
        pub deadline_status: Option<String>,
        pub linked_channel: Option<String>,
        pub archived_at: Option<chrono::DateTime<chrono::Utc>>,
        pub created_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct LapsedRow {
        pub id: uuid::Uuid,
        pub deadline: chrono::DateTime<chrono::Utc>,
        pub deadline_status: Option<String>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct PlacementRow {
        pub seq: i64,
        pub account_id: uuid::Uuid,
        pub placed_by: uuid::Uuid,
        pub placed_at: chrono::DateTime<chrono::Utc>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct SeatRow {
        pub id: uuid::Uuid,
        pub kind: String,
        pub prompt: Option<String>,
        pub link: Option<String>,
        pub occupant: Option<uuid::Uuid>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct SurfaceParentRow {
        pub type_tag: String,
        pub mode: Option<String>,
    }

    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct TreeNodeRow {
        pub id: uuid::Uuid,
        pub parent: Option<uuid::Uuid>,
        pub type_tag: String,
        pub mode: Option<String>,
        pub position: i32,
        pub created_by: uuid::Uuid,
        pub created_at: chrono::DateTime<chrono::Utc>,
        pub payload: serde_json::Value,
    }

    /// `queries/commission/add_component.sql`, typed against the migrated schema at generation time.
    pub async fn add_component(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        parent: uuid::Uuid,
        created_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
        payload: &serde_json::Value,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/add_component.sql"))
            .bind(id)
            .bind(commission_id)
            .bind(parent)
            .bind(created_by)
            .bind(created_at)
            .bind(payload)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/add_file.sql`, typed against the migrated schema at generation time.
    pub async fn add_file(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        uploaded_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/add_file.sql"))
            .bind(id)
            .bind(commission_id)
            .bind(uploaded_by)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/add_participant.sql`, typed against the migrated schema at generation time.
    pub async fn add_participant(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        user_id: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/add_participant.sql"))
            .bind(commission_id)
            .bind(user_id)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/add_surface.sql`, typed against the migrated schema at generation time.
    pub async fn add_surface(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        parent: uuid::Uuid,
        mode: &str,
        created_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/add_surface.sql"))
            .bind(id)
            .bind(commission_id)
            .bind(parent)
            .bind(mode)
            .bind(created_by)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/create_commission.sql`, typed against the migrated schema at generation time.
    pub async fn create_commission(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        title: &str,
        owner_id: uuid::Uuid,
        lifecycle: &str,
        visibility: &str,
        deadline: Option<chrono::DateTime<chrono::Utc>>,
        maturity: Option<&str>,
        graphic: Option<bool>,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/create_commission.sql"))
            .bind(id)
            .bind(title)
            .bind(owner_id)
            .bind(lifecycle)
            .bind(visibility)
            .bind(deadline)
            .bind(maturity)
            .bind(graphic)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/create_root_surface.sql`, typed against the migrated schema at generation time.
    pub async fn create_root_surface(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        mode: &str,
        created_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/create_root_surface.sql"
        ))
        .bind(id)
        .bind(commission_id)
        .bind(mode)
        .bind(created_by)
        .bind(created_at)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/current_placement.sql`, typed against the migrated schema at generation time.
    pub async fn current_placement(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Option<PlacementRow>> {
        sqlx::query_as(include_str!("../queries/commission/current_placement.sql"))
            .bind(commission_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/commission/declare_seat_node.sql`, typed against the migrated schema at generation time.
    pub async fn declare_seat_node(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        parent: uuid::Uuid,
        created_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/declare_seat_node.sql"))
            .bind(id)
            .bind(commission_id)
            .bind(parent)
            .bind(created_by)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/declare_seat_satellite.sql`, typed against the migrated schema at generation time.
    pub async fn declare_seat_satellite(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        kind: &str,
        prompt: Option<&str>,
        link: Option<&str>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/declare_seat_satellite.sql"
        ))
        .bind(id)
        .bind(commission_id)
        .bind(kind)
        .bind(prompt)
        .bind(link)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/declare_slot_node.sql`, typed against the migrated schema at generation time.
    pub async fn declare_slot_node(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        commission_id: uuid::Uuid,
        parent: uuid::Uuid,
        created_by: uuid::Uuid,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/declare_slot_node.sql"))
            .bind(id)
            .bind(commission_id)
            .bind(parent)
            .bind(created_by)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/declare_slot_satellite.sql`, typed against the migrated schema at generation time.
    pub async fn declare_slot_satellite(
        conn: impl sqlx::PgExecutor<'_>,
        node_id: uuid::Uuid,
        commission_id: uuid::Uuid,
        title: &str,
        notes: Option<&str>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/declare_slot_satellite.sql"
        ))
        .bind(node_id)
        .bind(commission_id)
        .bind(title)
        .bind(notes)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/delete.sql`, typed against the migrated schema at generation time.
    pub async fn delete(conn: impl sqlx::PgExecutor<'_>, id: uuid::Uuid) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/delete.sql"))
            .bind(id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/find.sql`, typed against the migrated schema at generation time.
    pub async fn find(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
    ) -> sqlx::Result<Option<CommissionRow>> {
        sqlx::query_as(include_str!("../queries/commission/find.sql"))
            .bind(id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/commission/find_file.sql`, typed against the migrated schema at generation time.
    pub async fn find_file(
        conn: impl sqlx::PgExecutor<'_>,
        key: uuid::Uuid,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Option<CommissionFileRow>> {
        sqlx::query_as(include_str!("../queries/commission/find_file.sql"))
            .bind(key)
            .bind(commission_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/commission/grant_view.sql`, typed against the migrated schema at generation time.
    pub async fn grant_view(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        account_id: uuid::Uuid,
        level: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/grant_view.sql"))
            .bind(commission_id)
            .bind(account_id)
            .bind(level)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/is_participant.sql`, typed against the migrated schema at generation time.
    pub async fn is_participant(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        user_id: uuid::Uuid,
    ) -> sqlx::Result<bool> {
        sqlx::query_scalar(include_str!("../queries/commission/is_participant.sql"))
            .bind(commission_id)
            .bind(user_id)
            .fetch_one(conn)
            .await
    }

    /// `queries/commission/lapsed_deadlines.sql`, typed against the migrated schema at generation time.
    pub async fn lapsed_deadlines(
        conn: impl sqlx::PgExecutor<'_>,
        now: chrono::DateTime<chrono::Utc>,
        terminal_lifecycles: &[String],
    ) -> sqlx::Result<Vec<LapsedRow>> {
        sqlx::query_as(include_str!("../queries/commission/lapsed_deadlines.sql"))
            .bind(now)
            .bind(terminal_lifecycles)
            .fetch_all(conn)
            .await
    }

    /// `queries/commission/load_tree.sql`, typed against the migrated schema at generation time.
    pub async fn load_tree(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Vec<TreeNodeRow>> {
        sqlx::query_as(include_str!("../queries/commission/load_tree.sql"))
            .bind(commission_id)
            .fetch_all(conn)
            .await
    }

    /// `queries/commission/place_append.sql`, typed against the migrated schema at generation time.
    pub async fn place_append(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        account_id: uuid::Uuid,
        placed_by: uuid::Uuid,
        placed_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<i64> {
        sqlx::query_scalar(include_str!("../queries/commission/place_append.sql"))
            .bind(commission_id)
            .bind(account_id)
            .bind(placed_by)
            .bind(placed_at)
            .fetch_one(conn)
            .await
    }

    /// `queries/commission/place_repoint_current.sql`, typed against the migrated schema at generation time.
    pub async fn place_repoint_current(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        account_id: uuid::Uuid,
        seq: i64,
        placed_by: uuid::Uuid,
        placed_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/place_repoint_current.sql"
        ))
        .bind(commission_id)
        .bind(account_id)
        .bind(seq)
        .bind(placed_by)
        .bind(placed_at)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/placement_log.sql`, typed against the migrated schema at generation time.
    pub async fn placement_log(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Vec<PlacementRow>> {
        sqlx::query_as(include_str!("../queries/commission/placement_log.sql"))
            .bind(commission_id)
            .fetch_all(conn)
            .await
    }

    /// `queries/commission/remove_node_delete.sql`, typed against the migrated schema at generation time.
    pub async fn remove_node_delete(
        conn: impl sqlx::PgExecutor<'_>,
        node: uuid::Uuid,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/remove_node_delete.sql"))
            .bind(node)
            .bind(commission_id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/remove_node_gate.sql`, typed against the migrated schema at generation time.
    pub async fn remove_node_gate(
        conn: impl sqlx::PgExecutor<'_>,
        node: uuid::Uuid,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Option<Option<uuid::Uuid>>> {
        sqlx::query_scalar(include_str!("../queries/commission/remove_node_gate.sql"))
            .bind(node)
            .bind(commission_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/commission/remove_node_renumber.sql`, typed against the migrated schema at generation time.
    pub async fn remove_node_renumber(
        conn: impl sqlx::PgExecutor<'_>,
        parent: uuid::Uuid,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/remove_node_renumber.sql"
        ))
        .bind(parent)
        .bind(commission_id)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/require_surface_parent.sql`, typed against the migrated schema at generation time.
    pub async fn require_surface_parent(
        conn: impl sqlx::PgExecutor<'_>,
        parent: uuid::Uuid,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Option<SurfaceParentRow>> {
        sqlx::query_as(include_str!(
            "../queries/commission/require_surface_parent.sql"
        ))
        .bind(parent)
        .bind(commission_id)
        .fetch_optional(conn)
        .await
    }

    /// `queries/commission/revoke_view.sql`, typed against the migrated schema at generation time.
    pub async fn revoke_view(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/revoke_view.sql"))
            .bind(commission_id)
            .bind(account_id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/seats.sql`, typed against the migrated schema at generation time.
    pub async fn seats(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
    ) -> sqlx::Result<Vec<SeatRow>> {
        sqlx::query_as(include_str!("../queries/commission/seats.sql"))
            .bind(commission_id)
            .fetch_all(conn)
            .await
    }

    /// `queries/commission/set_archived.sql`, typed against the migrated schema at generation time.
    pub async fn set_archived(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        archived_at: Option<chrono::DateTime<chrono::Utc>>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/set_archived.sql"))
            .bind(id)
            .bind(archived_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/set_deadline.sql`, typed against the migrated schema at generation time.
    pub async fn set_deadline(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        deadline: Option<chrono::DateTime<chrono::Utc>>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/set_deadline.sql"))
            .bind(id)
            .bind(deadline)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/set_deadline_status.sql`, typed against the migrated schema at generation time.
    pub async fn set_deadline_status(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        status: Option<&str>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/set_deadline_status.sql"
        ))
        .bind(id)
        .bind(status)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/set_direction_status.sql`, typed against the migrated schema at generation time.
    pub async fn set_direction_status(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        status: Option<&str>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/commission/set_direction_status.sql"
        ))
        .bind(id)
        .bind(status)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/commission/set_linked_channel.sql`, typed against the migrated schema at generation time.
    pub async fn set_linked_channel(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        channel: Option<&str>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/set_linked_channel.sql"))
            .bind(id)
            .bind(channel)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/set_maturity.sql`, typed against the migrated schema at generation time.
    pub async fn set_maturity(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        maturity: &str,
        graphic: bool,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/commission/set_maturity.sql"))
            .bind(id)
            .bind(maturity)
            .bind(graphic)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/commission/view_grant.sql`, typed against the migrated schema at generation time.
    pub async fn view_grant(
        conn: impl sqlx::PgExecutor<'_>,
        commission_id: uuid::Uuid,
        account_id: uuid::Uuid,
    ) -> sqlx::Result<Option<String>> {
        sqlx::query_scalar(include_str!("../queries/commission/view_grant.sql"))
            .bind(commission_id)
            .bind(account_id)
            .fetch_optional(conn)
            .await
    }
}

pub mod file {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct FileBlobRow {
        pub filename: String,
        pub content_type: String,
        pub byte_size: i64,
        pub bytes: Vec<u8>,
    }

    /// `queries/file/delete.sql`, typed against the migrated schema at generation time.
    pub async fn delete(conn: impl sqlx::PgExecutor<'_>, key: uuid::Uuid) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/file/delete.sql"))
            .bind(key)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/file/get.sql`, typed against the migrated schema at generation time.
    pub async fn get(
        conn: impl sqlx::PgExecutor<'_>,
        key: uuid::Uuid,
    ) -> sqlx::Result<Option<FileBlobRow>> {
        sqlx::query_as(include_str!("../queries/file/get.sql"))
            .bind(key)
            .fetch_optional(conn)
            .await
    }

    /// `queries/file/put.sql`, typed against the migrated schema at generation time.
    pub async fn put(
        conn: impl sqlx::PgExecutor<'_>,
        key: uuid::Uuid,
        filename: &str,
        content_type: &str,
        byte_size: i64,
        bytes: &[u8],
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/file/put.sql"))
            .bind(key)
            .bind(filename)
            .bind(content_type)
            .bind(byte_size)
            .bind(bytes)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

pub mod health {
    /// `queries/health/is_reachable.sql`, typed against the migrated schema at generation time.
    pub async fn is_reachable(conn: impl sqlx::PgExecutor<'_>) -> sqlx::Result<i32> {
        sqlx::query_scalar(include_str!("../queries/health/is_reachable.sql"))
            .fetch_one(conn)
            .await
    }
}

pub mod key_store {
    /// `queries/key_store/get.sql`, typed against the migrated schema at generation time.
    pub async fn get(conn: impl sqlx::PgExecutor<'_>, did: &str) -> sqlx::Result<Option<Vec<u8>>> {
        sqlx::query_scalar(include_str!("../queries/key_store/get.sql"))
            .bind(did)
            .fetch_optional(conn)
            .await
    }

    /// `queries/key_store/put.sql`, typed against the migrated schema at generation time.
    pub async fn put(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
        wrapped_keys: &[u8],
        key_version: i32,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/key_store/put.sql"))
            .bind(did)
            .bind(wrapped_keys)
            .bind(key_version)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

pub mod plc {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct PlcOperationRow {
        pub cid: String,
        pub op_type: String,
        pub prev: Option<String>,
        pub operation: serde_json::Value,
    }

    /// `queries/plc/append.sql`, typed against the migrated schema at generation time.
    pub async fn append(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
        cid: &str,
        op_type: &str,
        prev: Option<&str>,
        operation: &serde_json::Value,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/plc/append.sql"))
            .bind(did)
            .bind(cid)
            .bind(op_type)
            .bind(prev)
            .bind(operation)
            .bind(created_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/plc/latest_cid.sql`, typed against the migrated schema at generation time.
    pub async fn latest_cid(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
    ) -> sqlx::Result<Option<String>> {
        sqlx::query_scalar(include_str!("../queries/plc/latest_cid.sql"))
            .bind(did)
            .fetch_optional(conn)
            .await
    }

    /// `queries/plc/latest_op.sql`, typed against the migrated schema at generation time.
    pub async fn latest_op(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
    ) -> sqlx::Result<Option<PlcOperationRow>> {
        sqlx::query_as(include_str!("../queries/plc/latest_op.sql"))
            .bind(did)
            .fetch_optional(conn)
            .await
    }
}

pub mod profile {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct ProfileRow {
        pub did: String,
        pub handle: String,
        pub display_name: Option<String>,
        pub avatar_url: Option<String>,
    }

    /// `queries/profile/get.sql`, typed against the migrated schema at generation time.
    pub async fn get(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
        cutoff: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<Option<ProfileRow>> {
        sqlx::query_as(include_str!("../queries/profile/get.sql"))
            .bind(did)
            .bind(cutoff)
            .fetch_optional(conn)
            .await
    }

    /// `queries/profile/put.sql`, typed against the migrated schema at generation time.
    pub async fn put(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
        handle: &str,
        display_name: Option<&str>,
        avatar_url: Option<&str>,
        fetched_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/profile/put.sql"))
            .bind(did)
            .bind(handle)
            .bind(display_name)
            .bind(avatar_url)
            .bind(fetched_at)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

pub mod session {
    /// `queries/session/create.sql`, typed against the migrated schema at generation time.
    pub async fn create(
        conn: impl sqlx::PgExecutor<'_>,
        id: &str,
        data: &[u8],
        expiry_date: time::OffsetDateTime,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/session/create.sql"))
            .bind(id)
            .bind(data)
            .bind(expiry_date)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/session/delete.sql`, typed against the migrated schema at generation time.
    pub async fn delete(conn: impl sqlx::PgExecutor<'_>, id: &str) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/session/delete.sql"))
            .bind(id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/session/delete_expired.sql`, typed against the migrated schema at generation time.
    pub async fn delete_expired(
        conn: impl sqlx::PgExecutor<'_>,
        now: time::OffsetDateTime,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/session/delete_expired.sql"))
            .bind(now)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/session/load.sql`, typed against the migrated schema at generation time.
    pub async fn load(
        conn: impl sqlx::PgExecutor<'_>,
        id: &str,
        now: time::OffsetDateTime,
    ) -> sqlx::Result<Option<Vec<u8>>> {
        sqlx::query_scalar(include_str!("../queries/session/load.sql"))
            .bind(id)
            .bind(now)
            .fetch_optional(conn)
            .await
    }

    /// `queries/session/save.sql`, typed against the migrated schema at generation time.
    pub async fn save(
        conn: impl sqlx::PgExecutor<'_>,
        id: &str,
        data: &[u8],
        expiry_date: time::OffsetDateTime,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/session/save.sql"))
            .bind(id)
            .bind(data)
            .bind(expiry_date)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

pub mod user {
    /// Row shape read back from the prepared statement's metadata.
    #[derive(Debug, sqlx::FromRow)]
    pub struct UserRow {
        pub id: uuid::Uuid,
        pub did: String,
        pub created_at: chrono::DateTime<chrono::Utc>,
    }

    /// `queries/user/find.sql`, typed against the migrated schema at generation time.
    pub async fn find(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
    ) -> sqlx::Result<Option<UserRow>> {
        sqlx::query_as(include_str!("../queries/user/find.sql"))
            .bind(id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/user/find_by_did.sql`, typed against the migrated schema at generation time.
    pub async fn find_by_did(
        conn: impl sqlx::PgExecutor<'_>,
        did: &str,
    ) -> sqlx::Result<Option<UserRow>> {
        sqlx::query_as(include_str!("../queries/user/find_by_did.sql"))
            .bind(did)
            .fetch_optional(conn)
            .await
    }

    /// `queries/user/provision.sql`, typed against the migrated schema at generation time.
    pub async fn provision(
        conn: impl sqlx::PgExecutor<'_>,
        id: uuid::Uuid,
        did: &str,
        created_at: chrono::DateTime<chrono::Utc>,
    ) -> sqlx::Result<UserRow> {
        sqlx::query_as(include_str!("../queries/user/provision.sql"))
            .bind(id)
            .bind(did)
            .bind(created_at)
            .fetch_one(conn)
            .await
    }
}

/// Every INSERT/UPDATE/DELETE statement, as `namespace::function` — generated
/// classification consumed by the `no_bare_pool_writes` guard.
pub static WRITE_QUERY_FNS: &[&str] = &[
    "account::accept_invitation_flip",
    "account::accept_invitation_seat",
    "account::change_handle_audit",
    "account::change_handle_repoint",
    "account::create_account",
    "account::create_invitation",
    "account::create_owner_membership",
    "account::departure_delete_membership",
    "account::departure_rehome_children",
    "account::departure_revoke_invitations",
    "account::grant_role",
    "account::hard_delete_account",
    "account::hard_delete_invitations",
    "account::hard_delete_memberships",
    "account::revoke_invitation",
    "account::soft_delete",
    "account::transfer_demote_owner",
    "account::transfer_promote_heir",
    "actor_identity::create",
    "actor_identity::intern",
    "changelog::append",
    "commission::add_component",
    "commission::add_file",
    "commission::add_participant",
    "commission::add_surface",
    "commission::create_commission",
    "commission::create_root_surface",
    "commission::declare_seat_node",
    "commission::declare_seat_satellite",
    "commission::declare_slot_node",
    "commission::declare_slot_satellite",
    "commission::delete",
    "commission::grant_view",
    "commission::place_append",
    "commission::place_repoint_current",
    "commission::remove_node_delete",
    "commission::remove_node_renumber",
    "commission::revoke_view",
    "commission::set_archived",
    "commission::set_deadline",
    "commission::set_deadline_status",
    "commission::set_direction_status",
    "commission::set_linked_channel",
    "commission::set_maturity",
    "file::delete",
    "file::put",
    "key_store::put",
    "plc::append",
    "profile::put",
    "session::create",
    "session::delete",
    "session::delete_expired",
    "session::save",
    "user::provision",
];
