//! The contract → Rust generator (DD 40992770 decisions 4 and 11): `protox`
//! compiles the repo-root corpus in pure Rust (no system `protoc`),
//! `prost-build` emits message structs, `pbjson-build` emits canonical
//! ProtoJSON `serde` impls — lowerCamelCase keys (R1), absent-optional key
//! omission (R4), strict Timestamp grammar on parse (closes the
//! chrono-laxness gap, `contract/VERSIONING.md` §7.3).
//!
//! A library so the api crate's `contract_current` drift test can regenerate
//! into a temp dir and diff, exactly as `sqlx-rust-codegen`'s
//! `codegen_current` does for `queries.rs` — one generation body, two
//! callers, no way for the committed output to drift silently.

use std::path::Path;

use anyhow::Context;
use prost::Message;

/// The corpus files, relative to the contract root. Order is meaningless;
/// protox resolves imports.
pub const SOURCES: &[&str] = &[
    "zurfur/api/v1/problem.proto",
    "zurfur/api/v1/session.proto",
    "zurfur/api/v1/account.proto",
    "zurfur/api/v1/commission.proto",
];

/// Generate the committed module: `zurfur.api.v1.rs` (prost structs),
/// `zurfur.api.v1.serde.rs` (canonical ProtoJSON serde), and `mod.rs` gluing
/// them, into `out_dir`. Deterministic — same corpus, same bytes — which is
/// what makes the drift diff meaningful.
pub fn generate(contract_dir: &Path, out_dir: &Path) -> anyhow::Result<()> {
    std::fs::create_dir_all(out_dir).context("create generated out dir")?;

    let fds = protox::compile(SOURCES, [contract_dir])
        .context("protox compile of the contract corpus")?;

    let mut descriptor_bytes = Vec::new();
    fds.encode(&mut descriptor_bytes)
        .expect("descriptor set encodes");

    let mut prost_config = prost_build::Config::new();
    prost_config.out_dir(out_dir);
    prost_config.service_generator(Box::new(NoServices));
    prost_config.compile_well_known_types();
    prost_config.extern_path(".google.protobuf", "::pbjson_types");
    prost_config
        .compile_fds(fds)
        .context("prost-build over the descriptor set")?;

    // prost emits a module per package in the set, including google.api —
    // whose HttpRule types are route metadata consumed by the contract_routes
    // weld test, never runtime messages (the well-known types are extern_path'd
    // to pbjson-types and emit nothing). Drop the unused module so the
    // committed tree carries only what the api crate consumes.
    let google_api = out_dir.join("google.api.rs");
    if google_api.exists() {
        std::fs::remove_file(&google_api).context("remove unused google.api.rs")?;
    }

    pbjson_build::Builder::new()
        .register_descriptors(&descriptor_bytes)
        .context("pbjson register descriptors")?
        .out_dir(out_dir)
        .build(&[".zurfur.api.v1"])
        .context("pbjson-build serde impls")?;

    // The glue module, written by the generator so regeneration is atomic.
    std::fs::write(
        out_dir.join("mod.rs"),
        "\
// @generated by contract-gen — DO NOT EDIT. Regenerate: `just gen-contract`.
//! The contract's generated message types (DD 40992770): prost structs +
//! canonical-ProtoJSON serde, produced from `contract/zurfur/api/v1/*.proto`.
//! Drift from the corpus fails the `contract_current` test with a diff.
//!
//! One module includes BOTH generated files — the pbjson convention: the
//! serde impls reference the prost types by bare name, so they must share a
//! scope.

#[allow(clippy::all)]
#[rustfmt::skip]
mod v1 {
    include!(\"zurfur.api.v1.rs\");
    include!(\"zurfur.api.v1.serde.rs\");
}

pub use v1::*;
",
    )
    .context("write mod.rs")?;

    Ok(())
}

/// The decision-3 guard in code: a service generator that generates nothing,
/// so `service` blocks can never quietly become gRPC stubs.
struct NoServices;

impl prost_build::ServiceGenerator for NoServices {
    fn generate(&mut self, _service: prost_build::Service, _buf: &mut String) {
        // Deliberately empty: routes are declarations, not machinery
        // (DD 40992770 decision 3).
    }
}
