import prettier from 'eslint-config-prettier';
import fs from 'node:fs';
import path from 'node:path';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig, includeIgnoreFile } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');
// The committed ZesTTY twins (@generated .ts beside each .zts source,
// listed in .zts-twins — regenerated by `just gen-zts`) are compiler output:
// STYLE rules are off for them below, but they are deliberately NOT ignored —
// semantic rules, above all the DD 39944194 Effect-containment guard, must
// see the twins, because the twins are exactly how containment reaches code
// authored in .zts (DD 46596098 D6). A global ignore here would silently
// exempt ZesTTY code from the seam.
const ztsTwins = fs
	.readFileSync(path.resolve(import.meta.dirname, '.zts-twins'), 'utf8')
	.split('\n')
	.filter(Boolean);

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser
			}
		}
	},
	{
		// DD 39944194 containment: Effect exists only below the runes seam —
		// src/lib/server/** and *.server.ts. Everything above the seam receives
		// plain data and never sees a fiber.
		files: [
			'src/**/*.ts',
			'src/**/*.js',
			'src/**/*.svelte',
			'src/**/*.svelte.ts',
			'src/**/*.svelte.js'
		],
		ignores: ['src/lib/server/**', 'src/**/*.server.ts', 'src/**/*.server.spec.ts'],
		rules: {
			'no-restricted-imports': [
				'error',
				{
					paths: [
						{
							name: 'effect',
							message:
								'Effect is server-only (DD 39944194) — move this under src/lib/server/** or a *.server.ts.'
						}
					],
					patterns: [
						{
							group: ['effect/*', '@effect/*'],
							message: 'Effect is server-only (DD 39944194).'
						}
					]
				}
			]
		}
	},
	// Twins: style rules the ZesTTY emitter's shapes trip are off (the `e: any`
	// in the __ztsAbsurd keystone; `Empty {}` arm destructuring). Everything
	// else — including the containment guard above — stays live on them.
	...(ztsTwins.length
		? [
				{
					files: ztsTwins,
					rules: {
						'@typescript-eslint/no-explicit-any': 'off',
						'no-empty-pattern': 'off'
					}
				}
			]
		: []),
	{
		// Override or add rule settings here, such as:
		// 'svelte/button-has-type': 'error'
		rules: {}
	}
);
