// @generated by zts-check --twins from wiring-sample.zts
// The ZesTTY wiring canary (ZMVP-176) — a deliberately PERMANENT sample
// exercising all four language features, so the twins gate always has at
// least one pair to check and the toolchain can never silently rot. Not
// imported by the app; do not delete without replacing the canary.
import { type Result, Ok, Err } from "@zestty/core";
function __ztsAbsurd(x: never): never {
    const e: any = new globalThis.Error("zts: non-exhaustive match");
    e.ztsTag = x;
    throw e;
}
type Meter = {
    kind: "Empty";
} | {
    kind: "Filled";
    percent: number;
};
const Meter = {
    Empty: (): Meter =>({
            kind: "Empty"
        }),
    Filled: (percent: number): Meter =>({
            kind: "Filled",
            percent
        })
};
// v0.2.0 features (Phase 5): newtype, literal match + wildcard, and `?`.
type Label = (string) & {
    readonly __ztsNewtype: "Label";
};
const Label = (__ztsValue: string): Label =>__ztsValue as Label;
export function describe(m: Meter): string {
    return ((__m)=>{
        const __k = __m.kind;
        if (__k === "Empty") {
            const {} = __m;
            return "empty";
        }
        if (__k === "Filled") {
            const { percent } = __m;
            return `${percent}%`;
        }
        return __ztsAbsurd(__k);
    })(m);
}
export function clamp(n: number): Result<number, string> {
    return n < 0 ? Err("negative") : Ok(n);
}
export function tone(mood: "up" | "down" | "flat"): string {
    return ((__m)=>{
        if (__m === "up") {
            return "rising";
        }
        if (__m === "down") {
            return "falling";
        }
        return "steady";
    })(mood);
}
export function label(n: number): Result<Label, string> {
    const __t = clamp(n);
    if (__t.kind === "Err") {
        return __t;
    }
    const value = __t.value;
    return Ok(Label(`v${value}`));
}
