#!/usr/bin/env bash
#
# zts-twins.sh — committed-twins bookkeeping for ZesTTY (ZMVP-176, DD 46596098
# D2): maintains the style-ignore list (.zts-twins) and runs the guards
# zts-check itself does not cover. Self-locating; invoke from anywhere:
#
#   bash scripts/zts-twins.sh --write   # regenerate .zts-twins (after gen-zts)
#   bash scripts/zts-twins.sh --guard   # fail on: a twin whose .zts is gone
#                                       # (orphan), a .zts outside src/ (the
#                                       # tooling scopes to src — see below),
#                                       # or a stale .zts-twins list
#
# LC_ALL=C on every sort so the committed list never ping-pongs between
# machines with different collation locales.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root/frontend/web"

list_twins() {
    LC_ALL=C find src -name '*.zts' | sed 's/\.zts$/.ts/' | LC_ALL=C sort
}

write() {
    list_twins > .zts-twins
}

guard() {
    local status=0

    # ZesTTY sources live under src/ only — the twins list, the orphan sweep,
    # and the eslint/prettier wiring all assume it. A .zts anywhere else would
    # generate a twin the style tools then flag as unformatted authored code.
    local strays
    strays="$(LC_ALL=C find . -name '*.zts' \
        -not -path './src/*' -not -path './node_modules/*' \
        -not -path './.svelte-kit/*' -not -path './.zts-check/*')"
    if [ -n "$strays" ]; then
        echo "ERROR: .zts outside src/ (the twins tooling scopes to src):" >&2
        echo "$strays" >&2
        status=1
    fi

    # Orphans: a committed twin whose source is gone must fail, not linger
    # green — zts-check only compares twins that still have sources. grep
    # exit 1 = no twins at all (fine); >=2 = the scan itself failed, which
    # must not read as "no orphans".
    local twins rc=0
    twins="$(grep -rl --include='*.ts' '^// @generated by zts-check --twins' src 2>/dev/null)" || rc=$?
    if [ "$rc" -ge 2 ]; then
        echo "ERROR: orphan scan failed (grep exit $rc)" >&2
        exit "$rc"
    fi
    while IFS= read -r twin; do
        [ -n "$twin" ] || continue
        local src="${twin%.ts}.zts"
        if [ ! -f "$src" ]; then
            echo "orphan twin: $twin (its $src is gone — delete the twin or restore the source)" >&2
            status=1
        fi
    done <<< "$twins"

    # The committed list must match the sources, or the style tools are
    # ignoring the wrong set.
    if ! diff <(list_twins) .zts-twins >/dev/null; then
        echo 'ERROR: .zts-twins is stale — run `just gen-zts`' >&2
        status=1
    fi

    exit "$status"
}

case "${1:-}" in
    --write) write ;;
    --guard) guard ;;
    *) echo "usage: zts-twins.sh --write|--guard" >&2; exit 2 ;;
esac
