//! Embeds the migration set at compile time — the replacement for
//! `sqlx::migrate!`, whose proc macro left with the retired `macros` feature
//! (SQL-file separation: no query macro machinery in the build). Generates
//! `embedded_migrations.rs` in OUT_DIR: a sorted static array of
//! `(version, description, sql)`, consumed by `crate::migrator()`, which builds
//! the same `sqlx::migrate::Migrator` the macro used to expand to (identical
//! checksums — `Migration::new` hashes the same SQL text — so existing
//! `_sqlx_migrations` ledgers stay valid).

use std::{env, fs, path::PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));

    let migrations = manifest.join("migrations");
    println!("cargo:rerun-if-changed={}", migrations.display());

    let mut files: Vec<PathBuf> = fs::read_dir(&migrations)
        .expect("migrations directory exists")
        .map(|entry| entry.expect("dir entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "sql"))
        .collect();
    // sqlx orders migrations by the leading timestamp version; lexicographic
    // filename order is identical because the prefix is fixed-width.
    files.sort();

    let mut out = String::from(
        "/// Generated by build.rs from `migrations/` — do not edit.\n\
         static EMBEDDED_MIGRATIONS: &[(i64, &str, &str)] = &[\n",
    );
    for file in &files {
        let stem = file.file_stem().expect("sql file stem").to_string_lossy();
        let (version, name) = stem
            .split_once('_')
            .expect("migration files are named <version>_<name>.sql");
        assert!(
            version.chars().all(|c| c.is_ascii_digit()),
            "migration version prefix must be numeric: {stem}"
        );
        // Match sqlx's directory resolver: the description is the filename
        // remainder with underscores read as spaces.
        let description = name.replace('_', " ");
        // Manifest-relative, same reproducibility posture as the query registry.
        let rel = format!(
            "/migrations/{}",
            file.file_name()
                .expect("migration file name")
                .to_string_lossy()
        );
        out.push_str(&format!(
            "    ({version}, {description:?}, \
             include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {rel:?}))),\n"
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_migrations.rs");
    fs::write(dest, out).expect("write embedded_migrations.rs");
}
