//! `adapter-atproto` — the **public data boundary** of Zurfur.
//!
//! This crate is the only place that knows about the AT Protocol and the OAuth
//! handshake: it talks to the visitor's PDS to sign them in, mint identity, and
//! read public profile records, and it implements the domain port traits
//! ([`Authenticator`], [`ProfileSource`](domain::ports::ProfileSource),
//! [`DidMinter`](domain::ports::DidMinter)) so the rest of the system depends
//! only on roles, never on a protocol type. The jacquard library
//! (the AT Proto / OAuth client) is quarantined here — nothing protocol-shaped
//! leaks past this crate's surface (see DESIGN/"Domains and Applications").
//!
//! Surface (re-exported below):
//! - [`AtprotoAuthenticator`] — the real OAuth client ([`Authenticator`]).
//! - [`AtprotoProfileSource`] — public profile reads from the user's PDS
//!   ([`ProfileSource`](domain::ports::ProfileSource)).
//! - [`RealDidMinter`] — the live [`DidMinter`](domain::ports::DidMinter)
//!   (ZMVP-49): generates per-account secp256k1 rotation keys, signs an
//!   identity-only PLC genesis operation, derives the `did:plc`, custodies the
//!   keys via a [`KeyStore`](domain::ports::KeyStore), and submits to a PLC
//!   directory ([`NoopPlcDirectory`] in v1). [`StubDidMinter`] is kept as a
//!   synthetic floor stub for tests/dev.
//! - [`AtprotoAuthStore`] — Postgres-backed persistence for in-flight and
//!   established OAuth state, so a grant survives a restart or a replica move
//!   (ZMVP-12).
//!
//! `api` is the composition root and the only crate that decides which adapter
//! (this one, or `adapter-mem`) is live.

use std::sync::Arc;

use async_trait::async_trait;
use domain::{elements::did::Did, ports::Authenticator};
use fluent_uri::Uri;
use jacquard::identity::JacquardResolver;
use jacquard_oauth::{
    atproto::AtprotoClientMetadata,
    client::OAuthClient,
    scopes::Scopes,
    session::ClientData,
    types::{AuthorizeOptions, CallbackParams},
};
use smol_str::SmolStr;
use sqlx::PgPool;

/// Typed query functions generated by `query-codegen` from `queries/` — same
/// convention as adapter-pg (committed output, verified by the `codegen_current`
/// staleness gate that lives in adapter-pg's tests).
pub mod queries;

mod auth_store;
mod did_minter;
mod plc;
mod plc_directory;
mod profile;
mod public_records;
pub use auth_store::AtprotoAuthStore;
pub use did_minter::{RealDidMinter, StubDidMinter};
pub use plc_directory::{DirectoryConfig, NoopPlcDirectory, plc_directory_from_config};
pub use profile::AtprotoProfileSource;
pub use public_records::AtprotoPublicRecords;

/// The fully-applied jacquard OAuth client this crate drives: a
/// [`JacquardResolver`] (handle/DID resolution over `reqwest`) paired with the
/// Postgres-backed [`AtprotoAuthStore`], wrapped in `Arc` so the authenticator
/// is cheap to share. Kept as a private alias so this concrete protocol type
/// never appears in the crate's public signatures.
type Oauth = Arc<OAuthClient<JacquardResolver<reqwest::Client>, AtprotoAuthStore>>;

/// The real [`Authenticator`]: an OAuth client that talks to the visitor's PDS.
/// Holds jacquard's concrete client so nothing protocol-shaped leaks past this
/// crate — the rest of the system depends only on the `Authenticator` port.
pub struct AtprotoAuthenticator {
    oauth: Oauth,
}

impl AtprotoAuthenticator {
    /// Build the loopback OAuth authenticator with `redirect_uri` as its sole
    /// registered redirect target (see `build_oauth` for why that is fixed here).
    /// `pool` backs the persistent [`AtprotoAuthStore`] and is injected by `api`.
    pub fn new(redirect_uri: Uri<String>, pool: PgPool) -> Self {
        Self {
            oauth: build_oauth(redirect_uri, AtprotoAuthStore::new(pool)),
        }
    }
}

#[async_trait]
impl Authenticator for AtprotoAuthenticator {
    /// Resolves `handle` to its PDS, performs a Pushed Authorization Request
    /// (PAR) — minting and persisting the PKCE verifier + DPoP key into
    /// [`AtprotoAuthStore`] keyed by `state` — and returns the PDS authorization
    /// URL. Errors if the handle can't be resolved or the PDS is unreachable;
    /// the returned `Err` is jacquard's, surfaced as `anyhow`.
    async fn start(&self, handle: &str) -> anyhow::Result<String> {
        Ok(self
            .oauth
            .start_auth(handle, AuthorizeOptions::<jacquard::DefaultStr>::default())
            .await?)
    }

    /// Exchanges the callback params (`code`/`state`/`iss`) for tokens: jacquard
    /// looks up the in-flight request by `state`, runs the DPoP-bound token
    /// exchange against the PDS, persists the established session into
    /// [`AtprotoAuthStore`], and hands back the session. We read the verified
    /// `account_did` off that session and return it as a domain [`Did`].
    ///
    /// Errors if `state` doesn't match a saved request (expired/unknown/CSRF),
    /// the `iss` check fails, or the token exchange round-trip fails. The
    /// neutral param types keep protocol library types out of the port.
    async fn complete(
        &self,
        code: String,
        state: Option<String>,
        iss: Option<String>,
    ) -> anyhow::Result<Did> {
        let params = CallbackParams {
            code: code.into(),
            state: state.map(Into::into),
            iss: iss.map(Into::into),
        };
        let session = self.oauth.callback(params).await?;
        let did = session.data.read().await.account_did.clone();
        Ok(Did::new(did.to_string()))
    }
}

/// OAuth scopes requested at sign-in. `atproto` is the base AT Protocol scope; the
/// transitional `transition:generic` grant covers the legacy XRPC surface still in use.
/// This is a protocol concern owned by this adapter, not application configuration.
const OAUTH_SCOPES: &str = "atproto transition:generic";

/// Build the loopback OAuth client with `redirect_uri` registered as its sole redirect
/// target.
///
/// jacquard sends `redirect_uris[0]` in the PAR request and derives the loopback
/// `client_id` from this list, so the URI registered here is the one the PDS actually
/// redirects back to — there is no per-request override.
fn build_oauth(redirect_uri: Uri<String>, store: AtprotoAuthStore) -> Oauth {
    let scopes = Scopes::new(SmolStr::new_static(OAUTH_SCOPES))
        .expect("valid scopes")
        .convert();
    let config = AtprotoClientMetadata::new_localhost(Some(vec![redirect_uri]), Some(scopes));
    // The OAuth store holds two tiers of state: the in-flight auth request (PKCE
    // verifier + DPoP key, keyed by `state`) and, post-callback, the session token
    // set + DPoP key. Backing it with Postgres (`AtprotoAuthStore`) instead of an
    // in-process map is what lets a grant survive a restart, lets `/signin` and
    // `/signin-callback` land on different replicas, and gives jacquard's refresh
    // machinery a durable place to write rotated tokens (ZMVP-12).
    Arc::new(OAuthClient::new(
        store,
        ClientData {
            keyset: None,
            config,
        },
        reqwest::Client::new(),
    ))
}
