//! The public data boundary: the AT Protocol implementations of the domain
//! ports — OAuth sign-in, PDS profile/record reads and writes, and did:plc
//! minting with key custody.
//!
//! The jacquard client is quarantined here; nothing protocol-shaped leaks past
//! this crate's surface.

use std::sync::Arc;

use async_trait::async_trait;
use domain::{elements::did::Did, ports::Authenticator};
use fluent_uri::Uri;
use jacquard::identity::{JacquardResolver, resolver::ResolverOptions};
use jacquard_oauth::{
    atproto::AtprotoClientMetadata,
    client::OAuthClient,
    scopes::Scopes,
    session::ClientData,
    types::{AuthorizeOptions, CallbackParams},
};
use smol_str::SmolStr;
use sqlx::PgPool;

use crate::guarded_http::GuardedHttp;

/// Typed query functions generated by `query-codegen` from `queries/`.
pub mod queries;

mod auth_store;
mod did_minter;
mod guarded_http;
mod plc;
mod plc_directory;
mod profile;
mod public_records;
mod secret_vault;
pub use auth_store::AtprotoAuthStore;
pub use did_minter::{RealDidMinter, StubDidMinter};
pub use plc_directory::{DirectoryConfig, NoopPlcDirectory, plc_directory_from_config};
pub use profile::AtprotoProfileSource;
pub use public_records::AtprotoPublicRecords;
pub use secret_vault::SecretVault;

/// The applied jacquard OAuth client this crate drives, over the
/// Postgres-backed [`AtprotoAuthStore`]. Private, so the protocol type never
/// appears in a public signature.
type Oauth = Arc<OAuthClient<JacquardResolver<GuardedHttp>, AtprotoAuthStore>>;

/// The real [`Authenticator`]: an OAuth client that talks to the visitor's PDS.
pub struct AtprotoAuthenticator {
    oauth: Oauth,
}

impl AtprotoAuthenticator {
    /// Build the loopback OAuth authenticator with `redirect_uri` as its sole
    /// registered redirect target. `pool` backs the persistent
    /// [`AtprotoAuthStore`]; `vault` seals that store's secrets at rest. Errors
    /// when the system DNS configuration cannot be read.
    pub fn new(
        redirect_uri: Uri<String>,
        pool: PgPool,
        vault: SecretVault,
    ) -> anyhow::Result<Self> {
        let http = GuardedHttp::new()?;
        let store = AtprotoAuthStore::new(pool, vault);
        Ok(Self {
            oauth: build_oauth(redirect_uri, store, http),
        })
    }
}

#[async_trait]
impl Authenticator for AtprotoAuthenticator {
    /// Resolve `handle` to its PDS, run a Pushed Authorization Request (the
    /// PKCE verifier and DPoP key are persisted under `state`), and return the
    /// PDS authorization URL. Errors if the handle or PDS is unreachable.
    async fn start(&self, handle: &str) -> anyhow::Result<String> {
        Ok(self
            .oauth
            .start_auth(handle, AuthorizeOptions::<jacquard::DefaultStr>::default())
            .await?)
    }

    /// Exchange the callback params for tokens, persist the established
    /// session, and return the session's verified `account_did`.
    /// Errors on an unknown/expired `state`, a failed `iss` check, or a failed
    /// token exchange.
    async fn complete(
        &self,
        code: String,
        state: Option<String>,
        iss: Option<String>,
    ) -> anyhow::Result<Did> {
        let params = CallbackParams {
            code: code.into(),
            state: state.map(Into::into),
            iss: iss.map(Into::into),
        };
        let session = self.oauth.callback(params).await?;
        let did = session.data.read().await.account_did.clone();
        Ok(Did::from(did.to_string()))
    }
}

/// OAuth scopes requested at sign-in: the base `atproto` scope plus the
/// transitional `transition:generic` grant for the legacy XRPC surface.
const OAUTH_SCOPES: &str = "atproto transition:generic";

/// Build the loopback OAuth client with `redirect_uri` registered as its sole
/// redirect target — jacquard derives the loopback `client_id` from that list
/// and there is no per-request override. Every request it makes goes over `http`.
fn build_oauth(redirect_uri: Uri<String>, store: AtprotoAuthStore, http: GuardedHttp) -> Oauth {
    let scopes = Scopes::new(SmolStr::new_static(OAUTH_SCOPES))
        .expect("valid scopes")
        .convert();
    let config = AtprotoClientMetadata::new_localhost(Some(vec![redirect_uri]), Some(scopes));
    let client_data = ClientData {
        keyset: None,
        config,
    };
    let resolver = JacquardResolver::new(http, ResolverOptions::default());
    Arc::new(OAuthClient::new_from_resolver(store, resolver, client_data))
}
