//! @generated by sqlx-rust-codegen — DO NOT EDIT; run `just gen-queries` to refresh.
//!
//! Typed query functions, one per `queries/<namespace>/<name>.sql`. The
//! contract is inferred from the SQL itself (pg_query parse tree + the live
//! catalog + `Executor::describe` against the migrated schema at generation
//! time); leading `--` comments in a query file become the function's docs.
#![allow(clippy::too_many_arguments)]

pub mod auth_store {
    /// `queries/auth_store/delete_auth_req_info.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn delete_auth_req_info(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/auth_store/delete_auth_req_info.sql"
        ))
        .bind(state)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/delete_session.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn delete_session(
        conn: impl sqlx::PgExecutor<'_>,
        account_did: &str,
        session_id: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/auth_store/delete_session.sql"))
            .bind(account_did)
            .bind(session_id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/get_auth_req_info.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn get_auth_req_info(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
    ) -> sqlx::Result<Option<Vec<u8>>> {
        sqlx::query_scalar(include_str!("../queries/auth_store/get_auth_req_info.sql"))
            .bind(state)
            .fetch_optional(conn)
            .await
    }

    /// `queries/auth_store/get_session.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn get_session(
        conn: impl sqlx::PgExecutor<'_>,
        account_did: &str,
        session_id: &str,
    ) -> sqlx::Result<Option<Vec<u8>>> {
        sqlx::query_scalar(include_str!("../queries/auth_store/get_session.sql"))
            .bind(account_did)
            .bind(session_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/auth_store/save_auth_req_info.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn save_auth_req_info(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
        data: &[u8],
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/auth_store/save_auth_req_info.sql"))
            .bind(state)
            .bind(data)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/upsert_session.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn upsert_session(
        conn: impl sqlx::PgExecutor<'_>,
        account_did: &str,
        session_id: &str,
        data: &[u8],
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/auth_store/upsert_session.sql"))
            .bind(account_did)
            .bind(session_id)
            .bind(data)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

/// Every statement containing an INSERT/UPDATE/DELETE (CTEs included), as
/// `namespace::function` — structural classification from the parse tree.
pub static WRITE_QUERY_FNS: &[&str] = &[
    "auth_store::delete_auth_req_info",
    "auth_store::delete_session",
    "auth_store::save_auth_req_info",
    "auth_store::upsert_session",
];
