//! @generated by sqlx-rust-codegen — DO NOT EDIT; run `just gen-queries` to refresh.
//!
//! Typed query functions, one per `queries/<namespace>/<name>.sql`. The
//! contract is inferred from the SQL itself (pg_query parse tree + the live
//! catalog + `Executor::describe` against the migrated schema at generation
//! time); leading `--` comments in a query file become the function's docs.
#![allow(clippy::too_many_arguments)]

pub mod auth_store {
    /// `queries/auth_store/claim_browser_binding.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// Consume the browser binding of the auth request saved under `state` if it is
    /// still `browser_binding`: the one callback whose statement clears it claims the
    /// sign-in. A racing statement waits on the row lock, re-checks the cleared row
    /// and claims nothing.
    pub async fn claim_browser_binding(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
        browser_binding: &[u8],
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/auth_store/claim_browser_binding.sql"
        ))
        .bind(state)
        .bind(browser_binding)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/delete_auth_req_info.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn delete_auth_req_info(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/auth_store/delete_auth_req_info.sql"
        ))
        .bind(state)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/delete_session.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn delete_session(
        conn: impl sqlx::PgExecutor<'_>,
        account_did: &str,
        session_id: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/auth_store/delete_session.sql"))
            .bind(account_did)
            .bind(session_id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/delete_sessions_by_id.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// Delete every session stored under `session_id`, whatever its account: the
    /// cleanup for a sign-in that failed after its callback saved a session.
    pub async fn delete_sessions_by_id(
        conn: impl sqlx::PgExecutor<'_>,
        session_id: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/auth_store/delete_sessions_by_id.sql"
        ))
        .bind(session_id)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/get_auth_req_info.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn get_auth_req_info(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
    ) -> sqlx::Result<Option<Vec<u8>>> {
        sqlx::query_scalar(include_str!("../queries/auth_store/get_auth_req_info.sql"))
            .bind(state)
            .fetch_optional(conn)
            .await
    }

    /// `queries/auth_store/get_browser_binding.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// The browser-token hash of the auth request saved under `state`, if the request
    /// is younger than `lifetime_seconds`; a request without a binding, or one a
    /// callback has claimed, yields NULL.
    pub async fn get_browser_binding(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
        lifetime_seconds: i32,
    ) -> sqlx::Result<Option<Option<Vec<u8>>>> {
        sqlx::query_scalar(include_str!(
            "../queries/auth_store/get_browser_binding.sql"
        ))
        .bind(state)
        .bind(lifetime_seconds)
        .fetch_optional(conn)
        .await
    }

    /// `queries/auth_store/get_session.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn get_session(
        conn: impl sqlx::PgExecutor<'_>,
        account_did: &str,
        session_id: &str,
    ) -> sqlx::Result<Option<Vec<u8>>> {
        sqlx::query_scalar(include_str!("../queries/auth_store/get_session.sql"))
            .bind(account_did)
            .bind(session_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/auth_store/save_auth_req_info.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn save_auth_req_info(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
        data: &[u8],
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/auth_store/save_auth_req_info.sql"))
            .bind(state)
            .bind(data)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/save_bound_auth_request.sql`, contract inferred from the SQL against the migrated schema.
    ///
    /// Save an in-flight auth request together with the hash of the browser token
    /// that binds it, in one statement.
    pub async fn save_bound_auth_request(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
        data: &[u8],
        browser_binding: Option<&[u8]>,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/auth_store/save_bound_auth_request.sql"
        ))
        .bind(state)
        .bind(data)
        .bind(browser_binding)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/upsert_session.sql`, contract inferred from the SQL against the migrated schema.
    pub async fn upsert_session(
        conn: impl sqlx::PgExecutor<'_>,
        account_did: &str,
        session_id: &str,
        data: &[u8],
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/auth_store/upsert_session.sql"))
            .bind(account_did)
            .bind(session_id)
            .bind(data)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

/// Every statement containing an INSERT/UPDATE/DELETE (CTEs included), as
/// `namespace::function` — structural classification from the parse tree.
pub static WRITE_QUERY_FNS: &[&str] = &[
    "auth_store::claim_browser_binding",
    "auth_store::delete_auth_req_info",
    "auth_store::delete_session",
    "auth_store::delete_sessions_by_id",
    "auth_store::save_auth_req_info",
    "auth_store::save_bound_auth_request",
    "auth_store::upsert_session",
];
