//! @generated by query-codegen — DO NOT EDIT; run `just gen-queries` to refresh.
//!
//! Typed query functions, one per `queries/<namespace>/<name>.sql`, with
//! parameter and row types read from the live, migrated schema at generation
//! time (`Executor::describe`). Staleness is caught by the `codegen_current`
//! test, which regenerates against a fresh container and diffs this file.
#![allow(clippy::too_many_arguments)]

pub mod auth_store {
    /// `queries/auth_store/delete_auth_req_info.sql`, typed against the migrated schema at generation time.
    pub async fn delete_auth_req_info(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!(
            "../queries/auth_store/delete_auth_req_info.sql"
        ))
        .bind(state)
        .execute(conn)
        .await
        .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/delete_session.sql`, typed against the migrated schema at generation time.
    pub async fn delete_session(
        conn: impl sqlx::PgExecutor<'_>,
        account_did: &str,
        session_id: &str,
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/auth_store/delete_session.sql"))
            .bind(account_did)
            .bind(session_id)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/get_auth_req_info.sql`, typed against the migrated schema at generation time.
    pub async fn get_auth_req_info(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
    ) -> sqlx::Result<Option<Vec<u8>>> {
        sqlx::query_scalar(include_str!("../queries/auth_store/get_auth_req_info.sql"))
            .bind(state)
            .fetch_optional(conn)
            .await
    }

    /// `queries/auth_store/get_session.sql`, typed against the migrated schema at generation time.
    pub async fn get_session(
        conn: impl sqlx::PgExecutor<'_>,
        account_did: &str,
        session_id: &str,
    ) -> sqlx::Result<Option<Vec<u8>>> {
        sqlx::query_scalar(include_str!("../queries/auth_store/get_session.sql"))
            .bind(account_did)
            .bind(session_id)
            .fetch_optional(conn)
            .await
    }

    /// `queries/auth_store/save_auth_req_info.sql`, typed against the migrated schema at generation time.
    pub async fn save_auth_req_info(
        conn: impl sqlx::PgExecutor<'_>,
        state: &str,
        data: &[u8],
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/auth_store/save_auth_req_info.sql"))
            .bind(state)
            .bind(data)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }

    /// `queries/auth_store/upsert_session.sql`, typed against the migrated schema at generation time.
    pub async fn upsert_session(
        conn: impl sqlx::PgExecutor<'_>,
        account_did: &str,
        session_id: &str,
        data: &[u8],
    ) -> sqlx::Result<u64> {
        sqlx::query(include_str!("../queries/auth_store/upsert_session.sql"))
            .bind(account_did)
            .bind(session_id)
            .bind(data)
            .execute(conn)
            .await
            .map(|r| r.rows_affected())
    }
}

/// Every INSERT/UPDATE/DELETE statement, as `namespace::function` — generated
/// classification consumed by the `no_bare_pool_writes` guard.
pub static WRITE_QUERY_FNS: &[&str] = &[
    "auth_store::delete_auth_req_info",
    "auth_store::delete_session",
    "auth_store::save_auth_req_info",
    "auth_store::upsert_session",
];
